### PR TITLE
Hdrp/decals test sg on sg

### PR DESCRIPTION
**Pull request by roberto-renzetti-unity**
### Purpose of this PR
Added a test for decal projector where both the decal and the object being applied the decal use shader graph based materials, which exercise a different code path from our other decal test.
Since shader graph doesn't have the tessellation displacement implemented yet, I left the game objects for those hidden - once it gets implemented we can enable them and add their respective shader graph based materials to update the test. (I also left a copy of the original non-shader graph materials game objects disabled. The QA Engineer updating the test in the future (probably me) can use that as a reference and once all the game objects are updated the old original ones can be deleted)

---
### Release Notes
Please add any useful notes about the feature/fix that might be helpful for others.

---
### Testing status
**Katana Tests**: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?unity_branch=trunk&ScriptableRenderLoop_branch=hdrp%2Fdecals-test-sg-on-sg&automation-tools_branch=master

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)
1707_DecalsSG_on_SG

Any test projects to go with this to help reviewers?

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?unity_branch=trunk&ScriptableRenderLoop_branch=hdrp%2Fdecals-test-sg-on-sg&automation-tools_branch=master

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: None

---

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Hey, waiting for the update with the POM

**Comment by roberto-renzetti-unity** [comment]
I need to add the newest baseline image to this PR.

**Comment by sebastienlagarde** [comment]
I launched katana, you should be able to get a picture from the launch

**Comment by sebastienlagarde** [comment]
Hmm... I am still unable to produce an image with Katana.
I guess that you have a script in your PR that compare the result of shadergraph with the result of decal.shader right ? As it doesn't match it produce no image to update.

could you check that.

Note that I have push a commit that replace the FastACos by a arcosine (This avoid to rely on a subgraph that wasn't load/working on my computer). Don't think it affect the final result. Maybe the tolerance is too high? Thanks for looking at it.

**Comment by roberto-renzetti-unity** [comment]
Hi Sebastien
Thanks for the changes. I'll look into the tolerance issue - very strange as I added a whole column of POM material and decals, so it should have triggered the diff/new image... 
I'm out of the office - attending wedding of niece in Spain. I'll fix this all when I'm back on June 3rd.

**Comment by roberto-renzetti-unity** [comment]
@sebastienlagarde @RemyUnity I added the POM node to the test, and did the fix that @mattdatwork  suggested on https://unity.slack.com/archives/C3KQ4UD6V/p1560456312088600 I do see a strange flickering - might be a different problem. Git doesn't allow me to attach a video of it - I'll post it on the shadergraph channel.  Once I know that is unrelated to this PR I can run the tests in Katana and get the new baseline image for the test.

**Comment by sebastienlagarde** [comment]
@zeroyao Why?

**Comment by zeroyao** [comment]
> @zeroyao Why?

Oops didn't mean to!

**Comment by sebastienlagarde** [comment]
replace by https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4014

**Pull request closed without merging**
