### PR TITLE
Lw/update post processing version

### PR DESCRIPTION
**Pull request by Verasl**
### Purpose of this PR
Updated Post Processing to latest version

---
### Release Notes
Post Processing 2.1.6 > 2.1.7

---
### Testing status
**Katana Tests**: Running
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=lw%2Fupdate-post-processing-version&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] C# and shader warnings (supress shader cache to see them)

**Automated Tests**: N/A

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: Low

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by phi-lira** [comment]
Should we merge this PR?

**Comment by phi-lira** [comment]
Adding Kat for docs.

**Comment by phi-lira** [comment]
What's the status on this PR? Is it ok to merge?

**Comment by Katstodian** [comment]
There are no docs for post processing yet, so I’d prefer to not merge until there are.

**Comment by Chman** [comment]
This is for PPv2, which we do have documentation for. It's just the usual package version upgrade, it's not related with LWRP/Post-processing. Speaking of, this PR is probably pointless now as the new stuff is coming soon in master. If anything, this PR should be done against 19.2 and 19.1 compatible versions of LW.

**Comment by Katstodian** [comment]
Alright - thanks for clarifying :) I trust that Thomas knows what’s what completely.

Sendt fra min iPhone

**Pull request closed without merging**
