### PR TITLE
[Shader Graph] Enable Normal and Tangent Modification in Vertex (cross pipeline)

### PR DESCRIPTION
**Pull request by Kink3d**
# DO NOT MERGE BEFORE #4441

### Purpose of this PR
Implements #4442 on PBR, Unlit and Sprite SubShaders. Based on top of refactor in #4441.

---
### Release Notes
Changelog

---
### Testing status
**Katana Tests**: Running

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally

- Other: 

**Automated Tests**: None

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
Technical Risk: None, Low, Medium, High? Low - Does not change any existing behavior, adds new functionality and interpolations

Halo Effect: None, Low, Medium, High? Low - shouldn't affect existing graphs in any way

---

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
All good for me. Changelog is missing.

**Comment by Kink3d** [comment]
All green except `HDRP_GraphicTestRunner.8201_VertexAnimation`. Fixing.

**Comment by LandonTownsendUnity** [comment]
Shadergraph preview for PBR doesn't have lighting on this branch (there is still lighting on master for PBR graph shadergraph preview)
image

**Comment by LandonTownsendUnity** [comment]
PBR Graph in HDRP: Setting Vertex Position no longer works
image

**Comment by sebastienlagarde** [comment]
Hey @Kink3d , so there was a mismatch with your latest fix in "
Fix vertex animation in HDRP on PBR and Unlit master nodes". The main issue was that PBR and Unlit use "Vertex Position" naming and all HD master node where using position. So the code in animation template hlsl was failing on one case or the other. I convert everything to "Vertex position" to be consistent with PBR and unlit. It pass all the test, hope this will not introduce side effect :)

**Pull request merged**
