### PR TITLE
Make PBR sky compile again on xbox

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
The compiler gets confused at a fairly deep level with the current code path, to make it deviate, changing the number of samples work. This makes it compile again on xbox.

The new path is slower, but the shader is used in pre computation.

### CODE REVIEW

**Comment by EvgeniiG** [comment]
That compiles, but visually speaking it will outright fail because 90 is not a Fibonacci number. We probably need a better fix.

**Comment by FrancescoC-unity** [comment]
Gah, of course, I even thought of that, but forgot. 
Is 55 an acceptable value or is too low?

**Comment by EvgeniiG** [comment]
Probably good enough, we just need to get it running to start with.

**Comment by FrancescoC-unity** [comment]
Bumped to 144 and it compiles. It is probably overkill, but being precomputation as long as it compiles I'd say it's good.

**Pull request merged**
