### PR TITLE
Make decals work with multiple cameras

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Fix https://fogbugz.unity3d.com/f/cases/1194954/

---
### Testing status

**Manual Tests**: Yes
**Yamato**: https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Ffix-decal-multi-cam/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP_trunk/692256/job

### CODE REVIEW

**Comment by EvgeniiG** [comment]
No changelog because it will create a conflict.

**Comment by galgamion** [comment]
Hi,
In the unity public bug page it says that is Fixed in Unity 2020.1, it will be solved also in the previous version (2019.3)?

(I think that because is related with SRP it will be solved, if we update the SRP, but I'm not sure.)

**Comment by sebastienlagarde** [comment]
>No changelog because it will create a conflict.
That's not a good argument, it is easy for me to merge the change log, but adding them is more painful. Please add changelog :)

**Comment by EvgeniiG** [comment]
> > No changelog because it will create a conflict.
> That's not a good argument, it is easy for me to merge the change log, but adding them is more painful. Please add changelog :)

Okay, will do the next time. Was trying to help.

**Comment by EvgeniiG** [comment]
> Hi,
> In the unity public bug page it says that is Fixed in Unity 2020.1, it will be solved also in the previous version (2019.3)?
> 
> (I think that because is related with SRP it will be solved, if we update the SRP, but I'm not sure.)

I believe this C# fix is sufficient. The engine code also had several culling fixes, but I expect those to be rolled out to 2019.3 as well.

@seblagarde I added the backport tag.

**Pull request merged**
