### PR TITLE
Improve SSR ray biasing

### PR DESCRIPTION
**Pull request by EvgeniiG**
improve the ray biasing code to avoid self-intersections during the SSR traversal

### Testing status
**Katana Tests**: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=HDRP%2Fssr-bias&automation-tools_branch=master&unity_branch=trunk

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Need a changelog + need to update the SSR test (see katana), as it have change (the test exhibit both forward and deferred SSR)

**Comment by sebastienlagarde** [comment]
+ be more verbose on PR description :)

**Comment by EvgeniiG** [comment]
Will run Katana again.

**Comment by EvgeniiG** [comment]
Katana is green.

**Comment by EvgeniiG** [comment]
Changelog: "improve the ray biasing code to avoid self-intersections during the SSR traversal".

**Comment by sebastienlagarde** [comment]
> Changelog: "improve the ray biasing code to avoid self-intersections during the SSR traversal".

Thanks 

This is to add in this file: https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.high-definition/CHANGELOG.md

**Comment by EvgeniiG** [comment]
Done, but now there's a conflict, lol.

**Pull request merged**
