### PR TITLE
Fix Stereo Y-Flip for 2019.1

### PR DESCRIPTION
**Pull request by nerites**
### Purpose of this PR
The other PR with this changeset in it is gated behind design review of the interface between SRP and XR, so I'm splitting this fix off to expedite it. 

---
### Release Notes
- Fixes Y-flip in HDRP by using HDRP's Blit shader, which has been adapted to work with single-pass double-wide stereo rendering

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=stereoyflip&unity_branch=trunk&automation-tools_branch=add-platform-filter

**Manual Tests**: What did you do?
Manually tested single-pass double-wide (with and without postprocessing enabled) in the template workshop scene. 
image

**Automated Tests**: What did you setup?
Nothing yet.

Any test projects to go with this to help reviewers?
Used tempalte workshop scene.

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Low - new blit is protected by a unity version ifdef. 

**Halo Effect**: None, Low, Medium, High?
Low - Only affects final blit in the case that we're rendering stereo in post-2019.1

---
### Comments to reviewers
Sorry for the difficulties in getting my changesets through. I'll try and come up with a better workflow for driving future PRs.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Sadly the branch is based on master, so Katana will fail.

here is a copy paste from #dev-render pipe:

"Sorry but for the next few days we will need to follow a particular process for the PR on github.
Reasons: There is a different texture compressor on 2019.1 than on 2018.1, so katana screenshots are different + Katana is in a very bad state since a week which prevent us to do fast correction
Current state: Katana master with 2019.1 don't have correct reference screenshots, so it is red (I don't know why but this PR: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2162 doesn't seems to update reference screenshots correctly for HDRP.  I have another one in progress that are suppose to fix katana; https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2176 but katana is always down...). Katana release/2018.3 and 2018.3/staging is green

So until we fix katana on master. If you target a PR for 2018.3, *I will recommend to branch it from release/2018.3* and launch katana test with 2018.3/staging. Then we merge in release/2018.3 and backport to master. If you have created a branch from current master the katana test will fail on 2018.3...

Once we have fix the issues with master, we will be able to do branch from master and test against 2019.1.

Important: Screenshots are differents, so please, in any PR that add new test , mention it in the description. For a PR with new test that need to be backport, we are requiring to redo a set of screenshots, so we can't just cherry-pick in main branch, but need to cherrypick in intermediate branch, update the screenshots, then push"

so either you recreate a PR from a branch base on 2018.3/realease or wait that we fix master (which may happen monday).

**Comment by nerites** [comment]
Thanks for the info! The Y-flip fix however is compensating for a change that's landed in 2019.1 only so it doesn't make sense to backport to the 2018.3 branch. I'll just wait for Monday. (:

**Comment by sebastienlagarde** [comment]
@nerites So trunk on master (windows test) are now green and katana work again, please merge latest master and launch katana, then we are good to go. Thanks for your patience.

**Comment by nerites** [comment]
This change has been merged in along with https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2130 so we can cloe this.

**Pull request closed without merging**
