### PR TITLE
Fix for bug 1227659 : NullReferenceException when saving a shader graph in a URP project with the HDRP package also present

### PR DESCRIPTION
**Pull request by Nightmask3**
### Checklist for PR maker
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
  -> Don't think this needs a changelog because it doesn't repro in 8.x.x according to bug details, it was introduced within work on 9.0.0. Will still add one if needed. 
---
### Purpose of this PR

Fixes this bug: https://fogbugz.unity3d.com/f/cases/1227659/

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened URP test project and ran tests locally
- [x] Opened HDRP test project and ran tests locally
- [x] Opened Shader graph test project and ran tests locally

### CODE REVIEW

**Comment by Nightmask3** [comment]
The exception was thrown because an HDRP callback that gets called when the graph is saved was accessing a possibly undefined symbol if the HDRP package is present in a URP project, but isn't properly configured.

**Comment by Nightmask3** [comment]
Just moved the offending line of code past a check to see if the HDRP pipeline was properly defined for this project, and that returns out if it isn't.

**Comment by sebastienlagarde** [comment]
Does this fix need to be backport on 8.x / 7.x ?

**Comment by marctem** [comment]
> Does this fix need to be backport on 8.x / 7.x ?

@sebastienlagarde  It only needs a backport if you backport the bug. =) The offending line was merged to master last Friday in the staging merge.

**Pull request merged**
