### PR TITLE
Fix for all zero densities causing black spots -- default to whatever…

### PR DESCRIPTION
**Pull request by cdxntchou**
Fixing terrain density blend, previously you would have regions with all zero weights -- this PR adds a slight bias towards the base blendmap to avoid this situation.

### Purpose of this PR
Fixing terrain density blend, previously you would have regions with all zero weights -- this PR adds a slight bias towards the base blendmap to avoid this situation.

---
### Release Notes
Fixed terrain density blend causing black regions.

---
### Testing status
**Katana Tests**: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=hdrp%2FterrainDensityFix2&automation-tools_branch=add-platform-filter&unity_branch=trunk

**Manual Tests**: What did you do?  Tested density blends on Terrain in HDRP

**Automated Tests**: What did you setup?  None

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Near None

**Halo Effect**: None, Low, Medium, High?
Near None

---

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Add Katana please (note currently on amster 1501 fabric and 1701 fabric shader hdrp test fail).

**Comment by cdxntchou** [comment]
Katana Tests:   
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=hdrp%2FterrainDensityFix2&unity_branch=trunk&automation-tools_branch=master

**Comment by cdxntchou** [comment]
Merged master and rekicked tests again...

**Comment by sebastienlagarde** [comment]
Katana is green, failing test are unrelated to this PR and come from master. Meging.

**Comment by sebastienlagarde** [comment]
ah missed to update the change log. I will do it

**Pull request merged**
