### PR TITLE
Add ParticleSystem Shader Samples

### PR DESCRIPTION
**Pull request by richardkettlewell**
### Purpose of this PR

Adds a sample to HDRP containing a selection of Shader Graphs for use with the Particle System.
Recreates core functionality from the old Standard Particle Shaders in the built-in renderer.

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- Create empty HDRP project
- Open Package Manager window
- Import Particle System Shaders Sample
- Open SampleScene scene
- Enter Play Mode
- Observe each system and check it exhibits the desired functionality based on its assigned material/shader.

**Automated Tests**:  n/a

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: None

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
@richardkettlewell can you talk with @iM0ve (our QA), so he can check that all works correctly ? Or describe the step to test this PR in the description, so he can follow it. Thanks

**Comment by richardkettlewell** [comment]
> @richardkettlewell can you talk with @iM0ve (our QA), so he can check that all works correctly ? Or describe the step to test this PR in the description, so he can follow it. Thanks

Sure! Ping me on slack (@richardk) and we can discuss.

It's pretty simple: Import the sample, load SampleScene, and check that each particle system does what it should based on the name of the shader applied to it. I can answer any questions you might have.

**Comment by richardkettlewell** [comment]
I also updated the PR to include the testing steps.

**Comment by iM0ve** [comment]
image Found 2 small but important issues. Should be fixed before merging.
More details: https://confluence.hq.unity3d.com/pages/editpage.action?pageId=59058630

**Comment by iM0ve** [comment]
Both issues were fixed.

**Pull request merged**
