### PR TITLE
Disable PBR sky below ground

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Disable PBR sky below ground to avoid rendering garbage.

---
### Comments to reviewers
Maybe worth doing it on the CPU? Thoughts?

### CODE REVIEW

**Comment by TomasKiniulis** [comment]
Viewing underground also causes lighting changes for models. Which might not be a desired effect for the user when viewing from bottom to top
fXU9kNdL3n

**Comment by EvgeniiG** [comment]
I will see what I can do.

**Comment by EvgeniiG** [comment]
Please test the new version.

**Comment by TomasKiniulis** [comment]
@EvgeniiG Nice changes! Lighting issues do not occur anymore, but there's one more issue.
When underground, after modifying PBR sky settings does not bring the surface back to normal after going above ground
Steps to reproduce:
1. Go underground
2. Go to PBR sky Volume settings
3. Select "All" and immediately click "None"
4. Go above the surface and observe that land is still grey 
MLwiksdqE2

**Comment by EvgeniiG** [comment]
That's because our sky system bakes the probes when you edit the sky. I cannot fix that one.

**Comment by EvgeniiG** [comment]
Julien may be able to fix it, but not as a part of this PR.

**Comment by sebastienlagarde** [comment]
Please, don't forget changelog. I will add it.

**Comment by sebastienlagarde** [comment]
@EvgeniiG . I discussed with Julien about the sky issue and indeed it is on his side, so no worry for this PR. Can you merge HDRP/staging (I suppose the code conflict with the merge of exposure fix) + launch yamato. I expect some screenshots will need to be updated. Thanks

+ Add release note :)

**Comment by EvgeniiG** [comment]
Done
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Fblack-underground/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP/520071/job

**Pull request merged**
