### PR TITLE
Add pass for invoking OnRenderObjectCallback in forward renderer

### PR DESCRIPTION
**Pull request by HedvigAxelsson**
### Purpose of this PR
Fix issue [1122420 ](https://fogbugz.unity3d.com/f/cases/1122420/)by adding a pass that invokes OnRenderObjectCallback. This enables users to use GL.Line in OnRenderObject and thus draw lines in game view.

---
### Release Notes
Fix issue where GL.Lines did not work in game view when using scriptable renderer.

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [x] Checked new UI names with UX convention
- [x] Tested UI multi-edition + Undo/Redo
- [x] C# and shader warnings (supress shader cache to see them)
- [x] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: Low

---

### CODE REVIEW

**Comment by phi-lira** [comment]
@HedvigAxelsson what version of Unity contains this new API. Need to figure out in order to bump minimum required unity version.

Also, another point, speaking recently with @julienf-unity about another feature we thought about exposing in ScriptableRenderContext he raised the point we should stop adding API in the context (as it breaks command buffer execution) and add in the command buffer instead.

@stramit  thoughts?

**Comment by HedvigAxelsson** [comment]
The new API is in 2019.3.0a10

**Comment by phi-lira** [comment]
Alright, good to go on this one as soon as test passed.

**Comment by HedvigAxelsson** [comment]
@phi-lira Could you merge this, please?

**Comment by phi-lira** [comment]
OSX failing due to another unrelated issue.

**Pull request merged**
