### PR TITLE
Optimize loop: 1x FR & 2x QR => 4x FR

### PR DESCRIPTION
**Pull request by EvgeniiG**

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
image

Not sure it is better (left old, right, new)

**Comment by sebastienlagarde** [comment]
Maybe at execution it is faster, but this need to be measured

**Comment by EvgeniiG** [comment]
cos(psi) and sin(psi) are not scalarized (since the scalar unit does not support the use of trigonometry).
It's best if they are loaded directly from the constant buffer.

**Comment by EvgeniiG** [comment]
Obsolete.

**Pull request closed without merging**
