### PR TITLE
Change the terrain keywords to local [2019.2 only - Wait before merging]

### PR DESCRIPTION
**Pull request by zeroyao**
### Purpose of this PR
Change the terrain keywords to local. Requires 2019.2.0a9.
Trunk has them changed already (for builtin terrain shaders).

---
### Release Notes

---
### Testing status
Green:  https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=terrain-shader-local-keywords&unity_branch=trunk&automation-tools_branch=master

Manual tested in HD and LW test projects.

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- Other: 

**Automated Tests**: I've checked the terrain tests in HD & LW. They all have normal map enabled. They should provide good coverage for the change.

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: None

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
As it is 2019.2 only, we will wait a bit before merging this PR.

**Comment by zeroyao** [comment]
@sebastienlagarde Windows Gfx tests are failing. Investigating...

**Comment by zeroyao** [comment]
> @sebastienlagarde Windows Gfx tests are failing. Investigating...

Hmm trunk change is needed to fix this :( Will let you know when the fix has landed.

**Comment by zeroyao** [comment]
Trunk fix has landed to 2019.2.0a10. Running the gfx test again...

**Comment by zeroyao** [comment]
@sebastienlagarde https://artifacts-ui.bf.unity3d.com/proj57-Test_PlayMode_-_Windows/29257035_21_03_2019_05_15_22_%2B0000/logs/TestResults_playmode_HDRP_Tests.xml terrain tests are passing, but 8102_Transparent failed. Is that something known? (seems to have been there for a week since my last run)

**Comment by zeroyao** [comment]
@sebastienlagarde When will this PR be merged as we start to ship 2019.2 alpha builds?

**Comment by sebastienlagarde** [comment]
thanks for poking me, I have forget about it. Will merge now (after I relaunch test on katana with latest master)

**Comment by sebastienlagarde** [comment]
katana green (failing test are from master), merging

**Pull request merged**
