### PR TITLE
Fix forward clustered lighting with stereo rendering

### PR DESCRIPTION
**Pull request by fabien-unity**
### Purpose of this PR
Fix forward clustered lighting with stereo rendering (double-wide)

---
### Release Notes
This will not be needed once SPI is the only supported stereo mode.

---
### Testing status
**Katana Tests**: [green](https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?automation-tools_branch=add-platform-filter&ScriptableRenderLoop_branch=hdrp%2Fxr%2Fcluster-fix&unity_branch=trunk)

**Manual Tests**: HDRP test scene 1301 (SSS) on Windows10/Oculus

BEFORE (look at tile issues on the right eye: spotlight is clamped)
cluster-before

AFTER
cluster-after

**Automated Tests**: nothing

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: None

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Nice! Add a line in the changelog.md

**Comment by fabien-unity** [comment]
Please ignore the delete of VFXLabeledField.uss ... not sure how it got in this PR.

**Comment by mmikk** [comment]
Keep in mind that fptl only works when MSAA is disabled. When MSAA is enabled we run clustered only.

**Comment by fabien-unity** [comment]
FPTL is still not working with stereo (we need to replicate the same changes done to cluster: g_mScrProjection -> g_mScrProjectionArr).

**Pull request merged**
