### PR TITLE
Backport of PR 3369 (area light shadow near plane shift) 

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Same as https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/3369

Katana: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?automation-tools_branch=master&ScriptableRenderLoop_branch=HDRP%2Fbackport-nearplane-shift-area-light&unity_branch=2019.1%2Fstaging

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
8205_SceneDepthColorNodes  test fails, is it always failing on 19.1?

**Comment by sebastienlagarde** [comment]
>8205_SceneDepthColorNodes test fails, is it always failing on 19.1?
It come from master. Please merge master and relaunch, sohuld be good

**Comment by FrancescoC-unity** [comment]
But this is 

> > 8205_SceneDepthColorNodes test fails, is it always failing on 19.1?
> > It come from master. Please merge master and relaunch, sohuld be good

But this is for the backport, I can't merge master

**Comment by sebastienlagarde** [comment]
Sort. O mean 2019.1/release :p

**Comment by sebastienlagarde** [comment]
Sort. O mean 2019.1/release :p

**Pull request merged**
