### PR TITLE
[Shader Graph][Skip CI] Preview Generator Refactor

### PR DESCRIPTION
**Pull request by Kink3d**
### Purpose of this PR
Refactors preview shader generator to use generator code from `GenerationUtils`. Removes a lot of now legacy code.

Refactors required to do this:
- Remove generic type version of `MasterNode<T>`
- Remove all intermediate SubShader interfaces
- Move SubShader > Master node validity to method on `ISubShader`
- Change `ISubShader.GetSubShader` to take `AbstractMaterialNode` argument
- Add `SurfaceDescription` generation path for preview shader
- Move all `GetShader` paths to `GenerationUtil.GetShader`
- Move `xDescriptionInputs` templates to Shader Graph package.

---
### Release Notes
Changelog

---
### Testing status
**Katana Tests**: Running

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: Not testable :(

---
### Overall Product Risks
**Technical Risk**: Low - Refactor to use already tested generation system

**Halo Effect**: High - Touches all previews and 3 packages...

---
### Comments to reviewers
- Have tested previews for all nodes in isolation
- Have tested NaN = magenta logic

### CODE REVIEW

**Comment by phi-lira** [comment]
Please add XR qa.

**Comment by LandonTownsendUnity** [comment]
Do we have a list of bugs that this refactor is expected to fix, if any?

**Comment by LandonTownsendUnity** [comment]
Preview no longer uses reflection probe.
Current PR:
image
Master:
image
Preview of a PBR Shader in Universal with color set to white and metallic set to 1

**Comment by LandonTownsendUnity** [comment]
Test doc:
https://docs.google.com/document/d/15_NysyiF5mwxMqk8TGer7MDA5MnCyvqu7PlpBPcKPqw/edit?usp=sharing

Once the reflection problem is fixed (or I am sufficiently convinced it doesn't need to be fixed) then I will approve.

**Comment by LandonTownsendUnity** [comment]
There are some pretty significant shipstoppers. Please do not merge this without my approval.

**Comment by alindmanUnity** [comment]
@LandonTownsendUnity fix for subgraphs saving has been pushed, please take a look

**Comment by alindmanUnity** [comment]
currently the failures in Universal CI are consistent with master

**Comment by LandonTownsendUnity** [comment]
I did a quick smoke test of mostly things the automated tests can't cover (subgraph and node preview generation) and they seem to be working fine after the merge from Master.

**Comment by ellioman** [comment]
What is the status of this PR?

**Comment by alindmanUnity** [comment]
note for @LandonTownsendUnity the reflection probe issue you raised is now resolved

**Comment by marctem** [comment]
This is rolled into the Targets PR now so unnecessary.

**Pull request closed without merging**
