### PR TITLE
Improve light clipping and culling #2

### PR DESCRIPTION
**Pull request by EvgeniiG**
Same as https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4695

### CODE REVIEW

**Comment by EvgeniiG** [comment]
QA pass?

**Comment by TomasKiniulis** [comment]
@EvgeniiG sorry for the delay, checking https://fogbugz.unity3d.com/f/cases/1085873 does indeed resolve the jagged lines, but I'm still getting culling issues checking with area lights https://fogbugz.unity3d.com/f/cases/1085873. Can this be further improved?
XdKycJXw5y

**Comment by EvgeniiG** [comment]
@TomasKiniulis yes, we need to fix the issue at the C++ level as well.

**Comment by FrancescoC-unity** [comment]
Hey! Was looking at this PR (to check compatibility with another box light fix I had) and found that it has problems with shadows. In a setup like this: 
Unity_aFns0Inkfr

The light leaks like this: 

Unity_i0GEBJjk47


This does not happen on staging 

(Note that  without merging staging into this PR you'll also get tiny leaks like in [here](https://user-images.githubusercontent.com/43168857/69358621-6dc58180-0c87-11ea-8675-ddf0d7c0a7f5.png), but this is fixed in staging)

**Comment by EvgeniiG** [comment]
@FrancescoC-unity my changes have nothing to do with shadows. It only modifies the cookie code. Look at the diff. :-)
Or are you saying there's now a new shadow culling issue?

**Comment by EvgeniiG** [comment]
Is this a shadow culling issue?

**Comment by FrancescoC-unity** [comment]
> Is this a shadow culling issue?

I
> @FrancescoC-unity my changes have nothing to do with shadows. It only modifies the cookie code. Look at the diff. :-)

> Is this a shadow culling issue?


I assume, yes. 

Haven't dug too deep since we were full of stuff to do, but with staging the issue didn't show while it did show with this branch.

**Comment by sebastienlagarde** [comment]
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Fimprove-area-light-culling/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP_fast-trunk/1633516/job

**Pull request merged**
