### PR TITLE
Vertex anim HDRP

### PR DESCRIPTION
**Pull request by cdxntchou**
Adds vertex animation to HDRP master nodes
fixes shader compilation issues with master / HDRP changes
     removed emissiveIntensity from builtin data
     VertexColor and ScreenPosition were capitalized
fixes a few other minor bugs

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Not related to the PR. But I would like to move the master node that correspond to a shader into the Material folder. 

i.e I want to move HDPBR graph into Material\Lit\ShaderGraph
And later add the HDLit graph into it

And move HDUnlit into Material\Unlit\ShaderGraph

The objective of this move is to have a folder for a material that is self content.
To add a material, you just need to add the folder (and register the material in "material.hlsl" and it will work and appear in shader graph. This is useful for our shader dedicated to other vertical that can be plug and play (like StackLit) and distributed inside a single Zip.

Also I see a lot of code in HDPBR that will be share by all HD master node, so we will let a ShaderGRaph folder with a file containinng all these shared functions.

**Comment by cdxntchou** [comment]
FYI -- the 'fixes for merge with master'  builtinData.emissiveIntensity lines probably shouldn't be backported, assuming those changes in HDRP didn't make it back to 18.2 either.

**Comment by sebastienlagarde** [comment]
>the 'fixes for merge with master' builtinData.emissiveIntensity lines probably shouldn't be backported, >assuming those changes in HDRP didn't make it back to 18.2 either.

All change to HDRP are currently immediately backported to 18.2, so it is safe.
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pulls?q=is%3Apr+is%3Aclosed

**Comment by zadi0648** [comment]
Going to continue some more advanced testing since there is more time until the pull Wednesday

**Comment by cdxntchou** [comment]
Fixed two small issues, and remerged with master to resolve the conflict
(seb fixed one of the same issues I did in this PR, but also reformatted a few lines at the same time)

**Comment by pbbastian** [comment]
Note that pull request #1485 fixes an issue introduced in this PR, so make sure to backport that one too.

**Comment by cdxntchou** [comment]
Backported to 2018.2 branch in commit 9e438c42224e3a93d8e45aa28e9043002c38536a
https://github.com/Unity-Technologies/ScriptableRenderPipeline/commit/9e438c42224e3a93d8e45aa28e9043002c38536a

**Pull request merged**
