### PR TITLE
Add sun disk support to the PBR sky

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Add sun disk support to the PBR sky.
Also optimize EvaluatePbrAtmosphere() a little bit.
Also align 'screenSpaceShadowIndex'.

---
### Release Notes
Add sun disk support to the Physically Based sky.

---
### Testing status
**Katana Tests**: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=HDRP%2Fpbr-sky-sun-disk&automation-tools_branch=master&unity_branch=trunk

### CODE REVIEW

**Comment by EvgeniiG** [comment]
I still need to test and merge, but you can already take a look if you want.

**Comment by EvgeniiG** [comment]
Crashes because of the XR stuff locally, will need to update Unity.

**Comment by EvgeniiG** [comment]
I have a ton of tests failing to create a RTs on Katana. I guess someone broke something? Or is it a crappy Katana machine?

image

**Comment by EvgeniiG** [comment]
Similar issue when running tests locally. :-(

image

**Comment by EvgeniiG** [comment]
The sky seems to work locally, so should be OK to merge.

**Comment by EvgeniiG** [comment]
Running Katana again...

**Comment by sebastienlagarde** [comment]
It seems that the assert issue have appear a bit everywhere (I see it on 4 different katana), then disappear when we relaunched all the katana. We don't have the issue since 2 days, so not sure. But unrelated to this PR.

**Comment by sebastienlagarde** [comment]
katana is green (error remaining are from master), merging

**Pull request merged**
