### PR TITLE
Disable vsync on the main display when rendering to a XR device

### PR DESCRIPTION
**Pull request by fabien-unity**
### Purpose of this PR
Fix for https://fogbugz.unity3d.com/f/cases/1147581/

---
### Testing status

**Manual Tests**: What did you do?
- [x] Built a player

**Yamato**: [running](https://yamato.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/hdrp-xr-disable-vsync/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP_fast-trunk/980240/job)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
@DennisDeRykeUnity could you validate this PR? thanks

**Comment by sebastienlagarde** [comment]
@fabien-unity @DennisDeRykeUnity any progress on validation of this PR? Thanks

**Comment by DennisDeRykeUnity** [comment]
@sebastienlagarde I approve this review contingent upon "All HDRP CI - fast-trunk" passing on Yamato.  The previous run failed, and log info was no longer available, so I launched it again just now.  

I closed case 1147581 because this PR improves HDRP performance using tthe Stereo Instancing stereo method.  I am likely to open a separate bug because HDRP performance still has bad performance using the Multi Pass stereo method depending on how much of the viewport is occupied by geometry.  See case 1147581 for more details.

**Comment by sebastienlagarde** [comment]
Note: ok I will merge it like this. The change mainly affect standalone player, so it need to be tested in palyer which isn't cover by our automatic test. This will be checked when testing the package 7.2.0 and building player for VR.

**Comment by sebastienlagarde** [comment]
I have run playmode DXR, it is green except one test that is already failing on HDRP/staging

**Pull request merged**
