### PR TITLE
URP/Shadergraph/XR GPU Instancing Tests

### PR DESCRIPTION
**Pull request by soraryu**
### Purpose of this PR
Currently, enabling "GPU Instancing" on shadergraph shaders breaks them. Sometimes on Desktop, sometimes in VR. This is not tested against yet.
This PR adds
- a test inside ShaderGraph testing with materials that enable "GPU Instancing"
- a test inside ShaderGraphUniversalStereo testing which is essentially the same but in XR

---
### Testing status

**Manual Tests**: What did you do?
- [X] Opened test project + Run graphic tests locally
- [X] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [X] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

_InstancedRendering test inside ShaderGraph project:_
InstancedRendering
Note that this fails when you disable SRP Batcher on the URPAsset:
image
Also note that even when it works the shaders have errors and a lot of warnings:
image

_InstancedRendering test inside ShaderGraphUniversalStereo project:_
002_xr_InstancedRendering
Note that his currently fails as well on all XR rendering modes:
image

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: Low (stuff needs to be fixed so these tests pass again)

---
### Comments to reviewers
I'd like to point out that I'd consider the underlying issues **high priority**. Those shader errors even prevent making builds.

### CODE REVIEW

**Comment by soraryu** [comment]
@sophiaaar here too, thanks.

**Comment by alindmanUnity** [comment]
shader graph failures mentioned here should be fixed by a recent PR, if you could merge master and check. regardless a good test case to keep coverage on

**Comment by soraryu** [comment]
They are not, for Android at least, if we're talking about the same PR (can you post the #?)

**Comment by ROBYER1** [comment]
> shader graph failures mentioned here should be fixed by a recent PR, if you could merge master and check. regardless a good test case to keep coverage on

I too would like to know what PR fixed this as I have been keeping up to date with this repo and nothing has fixed the Android VR issues we are having with Oculus Quest.

**Comment by soraryu** [comment]
I rebased these on the latest master just now.

Findings:
- just after the rebase (so after the URP upgrade basically) all shaders were still pink. Opening them and pressing "Save" again made them work. **Note:** this means there are issues with the upgrader, I think.
- for reasons that I don't understand, the camera image produced by TestRunner looks different then what I can see when pressing Play in the Editor. (this happens for both Editor and Build Tests)

I can actually see that the last frame rendered by TestRunner seems to match the ref image, but the saved image is wrong:
image

**Comment by soraryu** [comment]
After merging in #4948 to testrun that it seems the tests are not succeeding since the method to capture frames during testing doesn't seem to work anymore in Single Pass Instanced.

Looks like only the left eye is captured for comparison, not both eyes.
image

**Comment by DennisDeRykeUnity** [comment]
@soraryu You are correct that the test framework captures monoscopic screenshots when Stereo Instancing is used.  This is why I have not yet moved the URP Stereo Graphics Tests from SPS (Double Wide) to Stereo Instancing.  One of my action items is to investigate this problem and file a formal bug and/or come up with a workaround.  Also, sorry that I have not yet reviewed your two PRs... hectic schedule!

**Comment by soraryu** [comment]
@DennisDeRykeUnity there's definitely bugs around that but they can be worked around.

What works for Stereo Capture is ScreenCapture.CaptureScreenshotIntoRenderTexture (which flips the result in Y but otherwise gives the right texture) and ScreenCapture.CaptureScreenshotAsTexture(ScreenCapture.StereoScreenCaptureMode.BothEyes) (which is correctly flipped but might be interpreted in the wrong color space).

**Comment by thomas-zeng** [comment]
Hi @soraryu,
Thanks for spending time iterating on PR! Just want to share my info around screen capture here: 
1. RenderTexture is a Unity internal texture object that handles additional rendering logic. It encodes image y-flip logic and more. Sometimes RenderTexture stores image y-flipped which is actually expected.
2. CaptureScreenshotAsTexture stores color info that could be consumed by GPU so it doesn't handle srgb logic required for showing up on the monitor(image looks dark)
3. CaptureScreenshot stores image on disk handling y-flip and srgb correction. So I think using CaptureScreenshot to capture things sounds great! 
4. Monoscopic capture issue you and dennis mentioned above sounds like a bug to me.

**Comment by soraryu** [comment]
@DennisDeRykeUnity I created a PR which fixes the testing issues with Single Pass and Single Pass Instanced, #5022. Would be great if you could take a look.

**Comment by DennisDeRykeUnity** [comment]
I made dev branch xr_sg_urp_dennisd from SRP master then merged in three dev branches from prefrontalcortex remote per three PRs to be reviewed:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4803
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5022
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4802

On Yamato I have launched "_ABV for SRP repository - fast-trunk" against branch xr_sg_urp_dennisd per link below.  Tomorrow I will compare these test results against SRP master. Also tomorrow in the Editor I plan to examine the new tests introduced by these PRs, and tinker with the screen capture workaround.  
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/xr_sg_urp_dennisd/.yamato%252Fupm-ci-abv.yml%2523all_project_ci_fast-trunk/754717/job

@soraryu Thank you for your contributions.  Sorry that it has taken me a while to start reviewing these.

**Comment by DennisDeRykeUnity** [comment]
@soraryu I am closing three of your PRs (#4803, #5022, and#4802) because I merged them into PR #5215 which has been merged into master.  See discussion above.  Thanks again for your contributions!

**Pull request closed without merging**
