### PR TITLE
Reference images for OSXPlayer/Metal tests

### PR DESCRIPTION
**Pull request by Chman**
### Purpose of this PR

Added the reference images for OSXPlayer/Metal tests.

---
### Testing status

[Yamato is red](https://yamato.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/universal%252Fosxplayer-metal-ref-images/.yamato%252Fupm-ci-universal.yml%2523Universal_OSX_Standalone_trunk/312468/job/artifacts) due to one failing test (`008_AdditionalLights`). Felipe is currently looking at it. Everything else is fine.

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: None

### CODE REVIEW

**Comment by phi-lira** [comment]
Is this PR ready to go?

**Comment by Chman** [comment]
It is for me.

**Comment by sebastienlagarde** [comment]
Ping. Any progress ?

**Comment by Verasl** [comment]
Just running Yamato again as test 008 should be fixed now

**Pull request merged**
