### PR TITLE
Fix Fog with URP & VFX

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
### Purpose of this PR
Fix fog integration with Universal render pipeline.

See : https://fogbugz.unity3d.com/f/cases/1177594/

I was only using "ComputeFogFactor" with actually return fog parameter. 
The newly "ComputeFogIntensity" provide a absolute fog density to ease VFX integration (initially, this code was directly in MixColor).

Additionally, I added a graphic test to cover a basic usage of fog with VFX :
image

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: Low

~*awaiting for yamato...* => 🍏 !~ Actually, require a green status on Universal too.

### CODE REVIEW

**Comment by PaulDemeulenaere** [comment]
```LGTM but my worry is with the soon coming work to add Volume based fog this will not work so well since you are working around the MixFogColor, but can cross that bridge when we get there```
Let me know when you have implemented it, initially I did a hack using MixColor : https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4463/commits/45f00e4a12ac2896d1f9b114e8d76cbe116ecacd but I think it was a wrong solution. We can work together for this future fog improvement.

**Comment by PaulDemeulenaere** [comment]
It can be merged @julienf-unity 
image

**Comment by phi-lira** [comment]
Runnning UniversalRP and ShaderGraph CI as this PR touches core shader file used by all of them.

**Comment by phi-lira** [comment]
Can't see the Windows64_Standlone test failure as I'm not on VPN. Could you check it?

**Comment by PaulDemeulenaere** [comment]
I'm relaunching them, it looks like a timeout : ```[15:37:09.323 INF] An error occurred while resolving packages:
  One or more packages could not be added to the local file system:
    com.unity.ide.visualstudio: connect ETIMEDOUT 35.238.21.138:443
    com.unity.xr.legacyinputhelpers: connect ETIMEDOUT 35.238.21.138:443```

**Comment by PaulDemeulenaere** [comment]
Now I got a lot of error : 
[87/96] TestStart 'UniversalGraphicsTests.085_GradingShadowsMidtonesHighlightsLDR'
[87/96] TestFinish
	name: UniversalGraphicsTests.085_GradingShadowsMidtonesHighlightsLDR
	result: FAILED
	message: Unhandled log message: '[Exception] NullReferenceException: Object reference not set to an instance of an object'. Use UnityEngine.TestTools.LogAssert.Expect
	duration: 0.016031 seconds
I will open the project manually 🤔

**Comment by PaulDemeulenaere** [comment]
I had to launch `All Universal CI` (due to standalone test)
Is there a known issue ?

**Comment by dkyeck** [comment]
fog is broken in LWRP 5.16.1. when using _ALPHAPREMULTIPLY_ON.
the capsules visible altho they shoud be hidden by fog use the built in lit shader and a simple shader created with shader graph.
as i can't see any changes to code in URP i guess it will be broken there as well...

Bildschirmfoto 2019-09-18 um 16 52 52

**Pull request merged**
