### PR TITLE
Changed settings icon with the text "Inspect" [Skip CI]

### PR DESCRIPTION
**Pull request by Nzollner**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

The issue was the settings icon used for a button to inspect a UniversalRenderPipelineAsset_Renderer was blurry on lower resolution screens as seen in the image bellow:
CogWheelBlurred

Fixed the issue by making the button display text which says "Inspect" instead of using the settings icon as seen in the image bellow:
Capture

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [x] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other:

### CODE REVIEW

**Comment by martint-unity** [comment]
I dont think that text is the right way of doing this. If the cogwheel isn't ok then try the icon with three dots instead. To keep consistency.
_Menu.png from resources. Try that

**Comment by phi-lira** [comment]
@Nzollner can you try the approach above suggested by Martin?

**Comment by Nzollner** [comment]
Yes I will look into that :)

**Comment by Nzollner** [comment]
I have tried to change it and this is what is looks like:
image

**Pull request merged**
