### PR TITLE
Psvr fixes

### PR DESCRIPTION
**Pull request by robinb-u3d**
### Purpose of this PR

Fix several bugs that show up when testing HDRP in VR on PlayStation VR and PS4.
* Tessellation shaders in VR will not compile on PS4.
* The CameraNode direction property in the shadergraph relied on implicit truncation from a float4x4 to a float3x3 which cases an error on PS4.

---
### Testing status

**Manual Tests**: What did you do?
- [X] Built a player
- [X] Ran the VR test project on PSVR to verify the issues were fixed.
- Other: 

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline
Ran the following: _ABV for SRP repository - fast-trunk

5 Jobs failed on this branch:
* [HDRP on Win_DX11_playmode on version fast-trunk](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/psvr-fixes/.yamato%252Fupm-ci-abv.yml%2523all_project_ci_fast-trunk/822350/job/pipeline)
* [HDRP on Win_DX11_playmode XR on version fast-trunk](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/psvr-fixes/.yamato%252Fupm-ci-hdrp.yml%2523HDRP_Win_DX11_playmode_fast-trunk/822337/job/pipeline)

These both fail on `HDRP_GraphicTestRunner.2008_Light_Volumetrics`. This test is also failing on the master branch at the moment see https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/master/.yamato%252Fupm-ci-hdrp.yml%2523HDRP_Win_DX11_playmode_fast-trunk/831034/job

XR version has lots of failure on both this version and [master](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/master/.yamato%252Fupm-ci-hdrp.yml%2523HDRP_Win_DX11_playmode%2520XR_fast-trunk/868512/job)

* [VFX_LWRP on Win_DX11_Standalone on version fast-trunk](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/psvr-fixes/.yamato%252Fupm-ci-vfx_lwrp.yml%2523VFX_LWRP_Win_DX11_Standalone_fast-trunk/822347/job/pipeline)
* [VFX_LWRP on Win_DX11_playmode on version fast-trunk](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/psvr-fixes/.yamato%252Fupm-ci-vfx_lwrp.yml%2523VFX_LWRP_Win_DX11_playmode_fast-trunk/822348/job/pipeline)

These are also failing on master.

* [VFXMain on Win_DX11_playmode on version fast-trunk](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/psvr-fixes/.yamato%252Fupm-ci-vfxmain.yml%2523VFXMain_Win_DX11_playmode_fast-trunk/822344/job/pipeline) - [also fails on master](https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/master/.yamato%252Fupm-ci-vfxmain.yml%2523VFXMain_Win_DX11_playmode_fast-trunk/868372/job)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by LandonTownsendUnity** [comment]
Did you test this on an actual PS4 VR to see if it fixed the problem?

**Comment by robinb-u3d** [comment]
VR test project was used on PS4 + PSVR to test that the fixes built and ran.

**Comment by LandonTownsendUnity** [comment]
Should platforms qa or xr-qa  be added to test this? I have one idea for a possible regression test (making sure that the changes to the camera node don't break existing shadergraphs, which I don't think it will) but I can't exactly do any testing on PS4 hardware where testing this is most important. I will approve it if it passes that regression test but if you feel like there is any technical risk, a team with access to a ps4 should have their qa added to do a very quick smoke test (just to test the code added to unityinstancing.hlsl, which I can't test due to lack of a PS4 set up.) If you tested a PS4 test project and made sure it worked properly (not just testing if it built) then it's probably not necessary, but I just want to make sure.

**Comment by sebastienlagarde** [comment]
The test from Robin is this scene: https://github.cds.internal.unity3d.com/unity/com.unity.template.hd.vr.git run on PS4.
This is the VR tutorial that contain of lot of HDRP effects and that we asked him to fix :)

**Comment by sebastienlagarde** [comment]
(Note: current failure on yamato are related to the C++ PR from Juho about on demand compute, they are also failing on master).

**Pull request merged**
