### PR TITLE
Precision fix with mobile GPU and our ACES fitting curve

### PR DESCRIPTION
**Pull request by Chman**
### Purpose of this PR
Fixed a precision issue with mobile GPU and our ACES fitting curve (detected on Universal + Android/GLES3). For some reasons our compiler does maths in mediump in this shader even though we request highp, so it will overflow pretty quickly with high specular or emissive values.

---
### Testing status
**Katana Tests**: [Running](https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=aces-fitting-precision&automation-tools_branch=master&unity_branch=trunk&sort=1-asc)

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: Med

### CODE REVIEW

**Comment by Chman** [comment]
Note: do not merge, it broke a test on HDRP.

**Comment by phi-lira** [comment]
Please add changelog.

**Comment by Chman** [comment]
Changelog added. Also updated the ref test images for the ACES test in HDRP due to a single rogue pixel in there.

**Comment by sebastienlagarde** [comment]
Katana is green, PR approved. Merging

**Pull request merged**
