### PR TITLE
Universal/fix zero length computebuffer

### PR DESCRIPTION
**Pull request by phi-lira**
### Purpose of this PR
- Fixed scene view and shader graph preview turning grey: https://fogbugz.unity3d.com/f/cases/1175094/
- Fixed errors about trying to create zero length compute buffers.
- Fixed VFX tests.
---
### Release Notes
 Added missing note for a Shader Graph preview fix. 
 The other fixes don't require changelog entries as they are regressions introduced only in master.

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: Extended Reflection Probes tests to contain per-object and sky probes.

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=universal/fix-zero-length-computebuffer&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: Medium. Contains core lighting changes.

**Halo Effect**: Medium. Affects Vulkan, Metal, PS4 and Xbox One.

---
### Comments to reviewers
 For now disabling the SSBO path. It's not fully tested and it contains some Vulkan binding issues that need more investigation.

### CODE REVIEW

**Comment by LandonTownsendUnity** [comment]
Any ideas on why the automated tests are failing? The failures seem pretty drastic

**Comment by LandonTownsendUnity** [comment]
I had the same bug that was shown in the automated test. Will attempt to find repro steps but for now I'm going to recommend that merging does not happen.

**Comment by LandonTownsendUnity** [comment]
Merely switching to this branch with a project open introduces PERMANENT bugs to that project. This bugs do not go away when you switch back to master branch, and restart unity. The bugs I've encountered are the scene drawing in the background of the VFX preview, the top half to 2/3rds of the editor not drawing when the VFX preview has been opened (persisting after you've closed the VFX preview), and the top of the VFX preview not clearing. DO NOT TEST THIS BRANCH ON A PROJECT THAT YOU'RE NOT PREPARED TO DELETE AFTERWARDS.

**Comment by LandonTownsendUnity** [comment]
Sorry about some of the messages I've sent if you've gotten emails about them, I made some mistakes and thought that this branch was responsible for the bugs I was encountering (it wasn't)

**Comment by LandonTownsendUnity** [comment]
Whatever is happening in the automated tests seems to be happening to me in the editor, even if your branch hasn't been opened on that project
image
Something could be broken in master

**Comment by LandonTownsendUnity** [comment]
This is odd, I ran the same automated tests that failed on Yamato on my machine, and they all passed with this branch.

**Comment by phi-lira** [comment]
VFXMain test is failing due to another reason (seems issue specific with Yamato, katana passes).

**Comment by LandonTownsendUnity** [comment]
Apologies for adding myself as a reviewer and then not approving the PR, I'm a bit new and still figuring out how things work, I'll try not to make that mistake in the future

**Pull request merged**
