### PR TITLE
Olento this is a message for you. 

### PR DESCRIPTION
**Pull request by phi-lira**
Olento cares and we also care. Meet me at Unite in the lounge tomorrow the 25th at 16:15.

### CODE REVIEW

**Comment by soraryu** [comment]
Can I join? :)

**Comment by 0lento** [comment]
Will do :D

**Comment by phi-lira** [comment]
This event quest is available for anyone that can find this message, by any means. I'll be in the lounge at 16:15, carrying Unity on my back and a "Dev" piece of armour.

**Comment by Chman** [comment]
I might drop by as well...

**Pull request closed without merging**
