### PR TITLE
Assign the default volume profile when creating a new HDRP Asset.

### PR DESCRIPTION
**Pull request by fredericv-unity3d**
### Purpose of this PR
Assign the default volume profile when creating a new HDRP Asset.
Fixes [1174426](https://fogbugz.unity3d.com/f/cases/1174426/)

---
### Release Notes
Fixes [1174426](https://fogbugz.unity3d.com/f/cases/1174426/)

---
### Testing status
**Katana Tests**: -

**Automated Tests**: -

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: High?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by iM0ve** [comment]
Looks like the last update might have introduced new issues
eFn3n6trIF

**Comment by sebastienlagarde** [comment]
@fredericv-unity3d PR is approve, but waiting for QA validation

**Comment by iM0ve** [comment]
Having issues with this one. I think this error may have come from the previous state of staging. If that is the case, could someone merge staging into the branch again ?
image

**Comment by iM0ve** [comment]
> Looks like the last commit might have introduced new issues
> eFn3n6trIF

I think the previously mentioned issue still needs fixing. Opening Wizard causes error spam @fredericv-unity3d

**Pull request merged**
