### PR TITLE
Removing the usage of the render queues to identify what is rendered using recursive rendering

### PR DESCRIPTION
**Pull request by anisunity**
This a the newer version of these PRs:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5733
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5579

### CODE REVIEW

**Comment by anisunity** [comment]
First issue was a bug, fixed. Second one was not a bug, @remi-chapelain we can discuss it if you want.

**Comment by anisunity** [comment]
Looking into the issues

**Comment by anisunity** [comment]
Fixed all the issues that were and the rest are behaviors by design

**Comment by iM0ve** [comment]
Need to update Recursive rendering documentation:
image

**Comment by sebastienlagarde** [comment]
So talk with Remi, the PR is clean, BUT Yamato test on XR fail for totally unknow reasons...
https://yamato-artifactviewer.prd.cds.internal.unity3d.com/7590937f-b331-42dd-9ba9-26b791ac8990%2Flogs%2FTestProjects%2FHDRP_Tests%2Fupm-ci~%2Ftest-results/TestReportV1.html

**Pull request merged**
