### PR TITLE
Remove ProbeWrapper

### PR DESCRIPTION
**Pull request by RSlysz**
### Purpose of this PR
HDProbe is already a wrapper between Planar and standard (HD) probes.
This PR remove old ProbeWrapper that just add complexity for no gain.

---
### Release Notes
Internal cleaning in reflection probe system : removing ProbeWrapper (use HDProbe instead)

---
### Testing status
**Katana Tests**:  https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=HDRP%2Freflection-probe%2Fremove-probe-wraper&unity_branch=2018.3%2Fstaging&automation-tools_branch=add-platform-filter

**Manual Tests**: worked locally

**Automated Tests**: Launched graphic test and ~~almost~~ every one related to reflection probes works. ~~(2207 fail but it seams to be a resolution update. Perhaps the latest big PR impacted used resolution parameters)~~

---
### Overall Product Risks
**Technical Risk**: Medium
(Cleaning moving some lines of code and cleaning of engine classes)

**Halo Effect**: Low-medium
(affect only reflection)

---

### CODE REVIEW

**Comment by RSlysz** [comment]
@sebastien-unity fixed issue graphic test 2207
It was computed capture position used in EnvLightData that did not match anymore real capture point.

**Comment by sebastien-unity** [comment]
@RSlysz I think you have the wrong Sébastien...

**Comment by RSlysz** [comment]
Well yes sorry :/

**Comment by RSlysz** [comment]
Introducing a regression shown in new graphic test 2210.
(investigating)

**Comment by RSlysz** [comment]
Rebased on top of big PR Update-HDRP-folder-organization

**Pull request merged**
