### PR TITLE
Autodesk Interactive Shader support

### PR DESCRIPTION
**Pull request by Thomasch-unity3d**
2018.3.0a9 adds new methods to the RenderPipelineAsset that the ModelImporter calls to find SRP shader implementations for FBX models with Autodesk Interactive materials ( formerly named Stingray material ).
This PR adds 3 shader graphs ( 1 for each variant of the Autodesk Interactive shader ) for both Lightweight and HD pipelines which are referenced in each pipeline RenderPipelineAssets implementations.

Note that this code does not compile for Unity versions lower than 2018.3.0a9 because the base methods in RenderPipelineAsset are not present in previous Unity versions.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
A comment here. Please create a branch on public github and not on a fork as we need to launch katana on it and we can't from a fork: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=MSAA_RT_REFACTOR&automation-tools_branch=add-platform-filter&unity_branch=trunk#

**Comment by phi-lira** [comment]
Hi could you provide more info about what this is. Is these interactive materials a first class citizen for Unity?

**Comment by Thomasch-unity3d** [comment]
> Hi could you provide more info about what this is. Is these interactive materials a first class citizen for Unity?

3DsMax and Maya provide a PBR material called 'Autodesk interactive' ( formerly named Stingray) and this material is supported by FBX. In the vanilla render pipeline, importing a Stingray material from FBX creates a 'standard (roughness setup)' material. It's the only material we have that allows a full mapping of all textures and parameters between DCCs and Unity and it is a first class citizen, particularly usefull in roundtripping workflows using Unity's C# FBX Exporter.

**Comment by Thomasch-unity3d** [comment]
> A comment here. Please create a branch on public github and not on a fork as we need to launch katana on it and we can't from a fork: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=MSAA_RT_REFACTOR&automation-tools_branch=add-platform-filter&unity_branch=trunk#

I rebased onto master and pushed the branch to the public repo, running tests on katana here : https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=standard-roughness-shader

**Comment by sebastienlagarde** [comment]
Thanks, waiting for katana

**Comment by sebastienlagarde** [comment]
Katana is green, merging.

**Comment by sebastienlagarde** [comment]
My bad, katana was not green, I have click on the wrong link

**Pull request merged**
