### PR TITLE
Renaming of obsolete style attribute names

### PR DESCRIPTION
**Pull request by hugoBourretDesmarais**
Renaming of obsolete style attribute names according to the new standards.

New names: https://docs.google.com/spreadsheets/d/1zMcnMgSZEIFSZhANTaO1eUPF3DngElW81UgbtGXcAi4/edit#gid=0.

### CODE REVIEW

**Comment by pbbastian** [comment]
I think we'll wait until around 2018.3 cut-off to merge this in, but thanks for updating our styles :)

**Comment by Kink3d** [comment]
@pbbastian are we merging this for 2019.1?

Also why did we go with `border-left-width-width`? :/

**Comment by hugoBourretDesmarais** [comment]
It was definitely a mistake. I replaced all the ```border-left-width-width``` with ```border-left-width```.

**Comment by pbbastian** [comment]
Yep, this would be a very good idea to merge for 2019.1

**Comment by zadi0648** [comment]
I can't seem to find a version of Unity that will work with this?  I'm getting

`The type or namespace name IRenderPipeline could not be found. Are you missing an assembly reference?`

Also I don't seem to have a way to contact Hugo as his slack account has been deactivated?

**Comment by zadi0648** [comment]
Nevermind, I see the conflicts. I'm going to remove myself for now, so that when I get readded I know when to review.

**Comment by sebastienlagarde** [comment]
Is this PR still active ?

**Comment by pbbastian** [comment]
@Kink3d I forgot, did you incorporate this in another PR?

**Comment by Antoine-Lassauzay** [comment]
Hello,

Hugo has finished his internship. We likely won't nurse this as we still support obsolete properties so it's up to you guys to close this or fix conflicts.

**Pull request closed without merging**
