### PR TITLE
Use opacity instead of the scattering distance to parametrize the PBR sky

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Use opacity instead of the scattering distance to parametrize the PBR sky

---
### Testing status
**Katana Tests**: No

**Manual Tests**: Yes

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: Low

---
### Comments to reviewers
Test it.

### CODE REVIEW

**Comment by EvgeniiG** [comment]
Before we do anything artists need to test this.
It was an artist request and yet I haven't received any feedback so far.

**Comment by pierre-unity** [comment]
image

With 2020.1 Alpha 5, I'm am unable to pick the PBR Sky in the visual settings, the sky type is an integer for some reasons. Do I need a specific build instead?

**Comment by sebastienlagarde** [comment]
@Unity-Technologies/gfx-qa-hdrp we still need a pass on this one, after the merge we have done other test and not sure the build work. Can you test to build a scene with this PR on windows, mac, ps4 and see if all works? thanks

**Comment by EvgeniiG** [comment]
@seblagarde not before artist feedback.

**Comment by EvgeniiG** [comment]
@pierre-unity I suggest trying .3, that's what I typically use.

**Comment by laurenth-unity** [comment]
Testing this today, sorry it took so long

**Comment by EvgeniiG** [comment]
Going to bump this thread...

image

**Comment by sebastienlagarde** [comment]
We have been agree to merge this PR and can start the next improvement.

**Pull request merged**
