### PR TITLE
Added support for stack lit for ray tracing effects.

### PR DESCRIPTION
**Pull request by anisunity**
Added the support for stack lit with a simple fallback for the performance mode. Added stack lit shaders in some tests.

### CODE REVIEW

**Comment by anisunity** [comment]
i probably missed something i'll check

**Comment by sebastienlagarde** [comment]
@remi-chapelain 
>Missing support for "Geometric Specular AA" in Stacklit SG Properties
what do you mean? not related to this PR

Anis if you can merge with HDRP/staging :)

**Comment by sebastienlagarde** [comment]
>I mean when this checkbox is checked in StackLit SG Master Node, the reflection in RT SSR become black.

ok so it is an issue already present. the geometryic AA use ddx/ddy instruction, so it shouldn't compile. OR I guess we replace it with "something", maybe 0 and then it could explain why there is no spec as we multiply by 0. Anis could you check? but it isn't related to this PR.

**Comment by anisunity** [comment]
I fixed the specular lobe and the geometric AA issue

**Pull request merged**
