### PR TITLE
documentation fix for various pages

### PR DESCRIPTION
**Pull request by bitinn**
### Purpose of this PR

Fix various misspelling and broken links in current documentations.

Make browsing the documentations on GitHub easier, but also make it compatible with static doc generation tools like [mkdocs](https://www.mkdocs.org).

(After jumping around between various documentation folders on this repo, I decide it's time to make other users' life easier)

---
### Release Notes

Clean up documentation for LWRP, HDRP and Shader Graph. Make future documentation site creation much easier.

A demo site can be found here: https://bitinn.github.io/ScriptableRenderPipeline/

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?

**Automated Tests**: What did you setup?

Any test projects to go with this to help reviewers?

**No code were modified**

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: Low

Should be 0 risk unless you are preparing for a complete different set of documentations

I do recommendation using `mkdocs`, for no other reason than it's very low impact and very easy to deploy.

---
### Comments to reviewers

I have left out a commit that includes the mkdocs config file, but you can see it on my other branch, literally just some symlinks and 2-line yml config.

- https://github.com/bitinn/ScriptableRenderPipeline/blob/mkdocs-integration/mkdocs.yml
- https://github.com/bitinn/ScriptableRenderPipeline/tree/mkdocs-integration/docs

### CODE REVIEW

**Comment by phi-lira** [comment]
@Katstodian please add release notes to changelog.md

**Comment by bitinn** [comment]
@phi-lira I thought about adding changelog originally but since this change took place across multiple packages (BUT doc only), I don't know whether it could go into existing 5.3.0 section or warrant a new 5.3.1 section for a patch-only release... either one depends on your release schedule, so I opted not to add a changelog.

**Comment by Katstodian** [comment]
@bitinn - I've spoken to @phi-lira offline. 
We're not going to add changelog entries for this, since they're minor fixes. For docs, we'll make changelog entries for Additions and Changes. If you ever make a PR for docs like this again, you can write the changelog entry under the Release Notes/PR Description, and the relevant docs writer can subtract and add in the correct section. :)

@pbbastian - Since @Kink3d is out sick, can you verify the Shader Graph elements?

**Comment by sebastienlagarde** [comment]
Sorry we take too much time to merge and get conflict with recent change in documentation in HDRP. I create a new PR with these change above here: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2686 as I can't access to the fork directly. Change are exactly the same, I will merge them

**Pull request closed without merging**
