### PR TITLE
GPU Terrain (2018.3) port to HDRP and LWRP

### PR DESCRIPTION
**Pull request by zeroyao**
Recreate of the branch gpu_terrain and PR #1687 because I don't know how to properly revert a merge.

### CODE REVIEW

**Comment by zeroyao** [comment]
@sebastienlagarde Code changes required by this PR has landed as 2018.3.0a9. TerrainLit.shader won't work properly without these changes. What should I do to bump the version requirement?

**Comment by sebastienlagarde** [comment]
And one last test. Please test if the terrain works in forward.
by Default HDRP is in deferred mode. Go to HDRP asset and in frameSettings, check "enable forward only". This will use the forward path. The result should be the same (except maybe some quality bring back as the data are not compressed in a Gbuffer).

**Comment by sebastienlagarde** [comment]
Note: katana is Green.

**Comment by zeroyao** [comment]
@sebastienlagarde Forward rendering fixed

**Comment by sebastienlagarde** [comment]
poking @JulienIgnace-Unity  just in case the change for the prepration of the motion vector prepass (that we haven't implemented), could have a side effect on PS4.

**Comment by zeroyao** [comment]
@sebastienlagarde Graphics test 1601_TerrainLit is added for testing:
* terrain rendering
* shading parity between a mesh renderer
* decals.

**Comment by zeroyao** [comment]
Green Katana: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=gpu-terrain&unity_branch=trunk&automation-tools_branch=add-platform-filter

**Comment by vdefeo** [comment]
Your Pull Request has been selected for a project-agnostic code review by [Aurea Central Reviewers Team](https://github.com/orgs/trilogy-group/teams/aurea-central-reviewers/members).

<details><summary>More information</summary>

_This is an initiative to improve overall code quality. If your change is **urgent**, you **don't** have to wait for our review._ 

_NOTE: This review **does not** replace your team's review._

</details>

**Comment by zeroyao** [comment]
@sebastienlagarde @EvgeniiG The issue on PS4 player is fixed (PR: https://ono.unity3d.com/unity/unity/pull-request/72766/_/graphics/update-lightmodepassindex-after-pass-removal). I think this PR is good to go now.

**Pull request merged**
