### PR TITLE
Support cookie on light backing for Disc Area Light

### PR DESCRIPTION
**Pull request by skhiat**
### Purpose of this PR
Support Cookie on light backing for Disc Area Light

For QA: Thing to check. 
Cookie on area (Rectangle and Disc) , point, spot, directional work correctly. 
Baking of those cookie work with GI.

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 
Back few times

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Fies/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP_fast-trunk/1564877/job

**Comment by sebastienlagarde** [comment]
I will backport this PR to 8.x 
Note to Qa: Laurent before leaving have done extensive testing of this PR, so we are good to go.

**Comment by TomasKiniulis** [comment]
Checked HDRP/staging and 8.x.x/release branches. Not getting cookie textures baked for any type of light. Filed a ticket here: https://fogbugz.unity3d.com/f/cases/1230240/

**Comment by TomasKiniulis** [comment]
@skhiat Might be a good idea to add graphics test scene for baked cookies

**Pull request merged**
