### PR TITLE
Improve the noise used by the volumetric lighting system

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
- Improved the noise used by the volumetric lighting system.
- Removed the "slice distribution uniformity" parameter.

---
### Testing status

**Manual Tests**: Visuals require testing.

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Fvol-noise-staging/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP_trunk/927623/job

---
### Comments to reviewers
Need to update docs.

More details about the noise below...

The old noise we were using was crappy white noise. The new noise is the 3D correlated multi-jittered noise.
The old noise was all-frequency, so it contained plenty of low frequencies that were challenging to remove during reprojection or filtering/blur pass. The new noise is high-frequency, so the visuals should be less grainy after reprojection and/or filtering/blurring. There may or may not be more details in the image.

Either filtering or reprojection is required for volumetrics, otherwise the results are simply too noisy to use.

### CODE REVIEW

**Comment by EvgeniiG** [comment]
Yamato is broken, can't test:

image

**Comment by EvgeniiG** [comment]
Managed to launch it...

**Comment by EvgeniiG** [comment]
Undersampling still sometimes results in structured artifacts, but I have no idea why.

image

**Comment by EvgeniiG** [comment]
I kind of wonder if it's shadow bias or something completely unrelated like that...

**Comment by EvgeniiG** [comment]
It may have to do something with the fixed partitioning along the Z axis into slices. Not sure.

**Comment by iM0ve** [comment]
Im unsure why yamato says 102 playmode tests failed. I ran them locally and only 10 failed. Some are not related, but a few are relevant and would require an update (2008_Light_Volumetrics, 5003_Fog_DensityVolumesShadows, 5008_FogFiltering)

Also could you please explain more about how  "noise was improved?" I am comparing outputs of the automated test scene. I notice that the PR made it "noisier", is that expected?

Before:
image

After:
image

**Comment by EvgeniiG** [comment]
Are you testing with reprojection enabled? I assume not.

**Comment by iM0ve** [comment]
Not finished but this is my test progress so far:
https://confluence.unity3d.com/display/HDRP/Improve+the+noise+used+by+the+volumetric+lighting+system

**Comment by sebastienlagarde** [comment]
@EvgeniiG @laurenth-unity A comment on QA result? Laurent could you try the change? thanks

**Comment by EvgeniiG** [comment]
I would need to investigate. It's not obvious why it's not better.

**Comment by EvgeniiG** [comment]
Next iteration: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5524

**Pull request closed without merging**
