### PR TITLE
Use real types for compute shadow sampling

### PR DESCRIPTION
**Pull request by jessebarker**
### Purpose of this PR
Allow shadow sampling using "real" typed data.  Previous attempts either left shadow sampling incompatible (mixing half and float interfaces in the plumbing between core and HDRP) - this is the current state of master, or broken for mobile platforms.

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [ x] Opened test project + Run graphic tests locally
- [ x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ x] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Low
**Halo Effect**: None, Low, Medium, High?
Low - Desktop should be unaffected, and Universal does not use the compute sampling routines.
---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
I am fine with the change, but Kaychang is right. Regarding UV with fp16 you can only sample 1kx1K texture correctly, if you have higher resolution( like our shadow atlas), you should have precision issue.

Thought? Maybe you could make some test with a 4kx4k atlas, for the cascade shadow map just to check impact of the change at the edge of the shadow?

**Comment by sebastienlagarde** [comment]
this could also be a valid constraint, on mobile we max the size at 1K

**Comment by jessebarker** [comment]
I think I'm confused.  Are you worried about the theoretical limit (minimum distinguishable value) of fp16 (1/2048), or GPUs that don't support denormalized numbers (and would have an enormous zero hole in fp16)?  I'm not suggesting we push our luck, but 2048x2048 (and not a pixel more :-)) should be doable on a good GPU (assuming sane RNE and denorm behavior).

**Comment by jessebarker** [comment]
(I'm not opposed to a 1Kx1K limit if it will keep reasonable quality)

**Comment by kaychang-unity** [comment]
I agree that in theory, there shouldn't be an issue with sampling individual texels in a 2K texture with uv coordinates at half precision.
Empirically, I did saw sampling artefacts though, but I never dug deeper on the exact root cause (this could be some issue with the interpolation of the uv maybe, or other related math at half precision?).

**Comment by sebastienlagarde** [comment]
ok let's merge and we will see with time :)

**Pull request merged**
