### PR TITLE
Decal fade factor, fade start, draw distance automated test

### PR DESCRIPTION
**Pull request by TomasKiniulis**
Added automated test scene to check decals fade factor, fade start and draw distance values.

Scene contains 3 decals with draw distance of 20 and one decal with draw distance 1
Decal values with draw distance of 20:
1. Start Fade - 100, Fade Factor - 100
2. Start Fade - 30, Fade Factor - 80
3. Start Fade - 80, Fade Factor - 30

Decal with draw distance of 1 should not be drawn by the camera

image

Link to katana: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?automation-tools_branch=master&ScriptableRenderLoop_branch=decals-test-fadeFactorAndDistance&unity_branch=trunk

### CODE REVIEW

**Comment by RemyUnity** [comment]
You probably want to merge that branche in HDRP/staging and not master.

Run the graphic tests on Katana and add the Katana link in the description please.

**Comment by sebastienlagarde** [comment]
For this particular Pr it is fine to merge  in master. Next time indeed, plan for HDRP/staging

**Comment by sebastienlagarde** [comment]
Hmm.. looking at the test, do you have a decal shader graph version also ?

**Comment by TomasKiniulis** [comment]
> Hmm.. looking at the test, do you have a decal shader graph version also ?

Added right now. Looks like this.

image

**Comment by sebastienlagarde** [comment]
Please add the link to the katana (https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=decals-test-fadeFactorAndDistance&automation-tools_branch=master&unity_branch=trunk#) in the PR description and update here with a comment to say it is green (when it finish). THanks!

**Comment by TomasKiniulis** [comment]
> Please add the link to the katana (https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=decals-test-fadeFactorAndDistance&automation-tools_branch=master&unity_branch=trunk#) in the PR description and update here with a comment to say it is green (when it finish). THanks!

Play mode test successfully finished and now it is green: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders/proj57-Test%20PlayMode%20-%20Windows/builds/4893?ScriptableRenderLoop_branch=decals-test-fadeFactorAndDistance&automation-tools_branch=master&unity_branch=trunk

**Pull request merged**
