### PR TITLE
Allow for transparent objects to write to velocity [Wait C++ PR] 

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Exactly the same as https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2859 , but for a github client issue (must have corrupted something) I completely lost access to the repo I used for the branch. 

This is the same thing, but in a repo I can control.

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
C++ PR landed in trunk, backport to 2019.1 PR started .

Will now fix the merge issues

**Comment by FrancescoC-unity** [comment]
Backport landed in 2019.1/staging

**Comment by sebastienlagarde** [comment]
Katana is green except test that where failing on master. all good

**Comment by FrancescoC-unity** [comment]
I commited few files by mistake alongside with the merge. Let me revert them.

**Pull request merged**
