### PR TITLE
Fix some typos in the debug menu

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Fix some typos (but not all, see bug: https://fogbugz.unity3d.com/f/cases/edit/1224594/ ) in debug menus.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
be sure it work in the debug menu after this change

**Comment by FrancescoC-unity** [comment]
> be sure it work in the debug menu after this change

Most stuff still works, but I realised some shader includes need refactoring. Will patch it  up and update the PR.

**Comment by FrancescoC-unity** [comment]
> > be sure it work in the debug menu after this change
> 
> Most stuff still works, but I realised some shader includes need refactoring. Will patch it up and update the PR.

Done

**Comment by iM0ve** [comment]
Some shaders do not compile on this branch. They are Cyan forever. Only tested mac. Was compiling on master.

Screen Shot 2020-03-13 at 11 52 57

Repro steps:
Enable Albedo in Material->Common Material Properties

**Comment by sebastienlagarde** [comment]
@FrancescoC-unity could you create backport PR for those? thanks

**Pull request merged**
