### PR TITLE
LWRP (Universal) Metal OSX reference images

### PR DESCRIPTION
**Pull request by VladNeykov**
### Purpose of this PR
Adding ref image for OSX Metal for the VFX graph, as per:
https://fogbugz.unity3d.com/f/cases/1174901/

---
### Release Notes
Most of the images will need to be replaced once the GPU sorting bug is resolved:
https://fogbugz.unity3d.com/f/cases/1117644/

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?

**Halo Effect**: None, Low, Medium, High?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by VladNeykov** [comment]
@sophiaaar  Only adding OSX Metal ref images, OpenGLCore does not support compute shaders and can't run the VFX Graph

**Comment by phi-lira** [comment]
Heads up. I had to update recently (early this week) the test 005 image reference for LWRP due to one issue with scenes being shared between pipeline and post-processing. Make sure you merge master to double check if you need to update the OSX image as well.

**Comment by sophiaaar** [comment]
Some of these results look like the wrong image is being used as the reference - could you please verify?

**Comment by VladNeykov** [comment]
> Some of these results look like the wrong image is being used as the reference - could you please verify? And the Player tests still need images

Is it the ones which have missing particles? (multi output, gradient, and bounds)
If so, this is the note that these will have to be updated once the GPU sorting bug is fixed, as it makes particles disappear. This will be consistent though, so these tests ought to pass, and should only fail once the bug is resolved.

I've added OSX standalone player images and re-ran the editor tests.
Will run them again from scratch tomorrow to confirm that they are stable.

**Comment by VladNeykov** [comment]
@sophiaaar Re-ran today, looks stable.

**Comment by sophiaaar** [comment]
@VladNeykov can you re-run on yamato so the results appear here?

**Comment by VladNeykov** [comment]
> @VladNeykov can you re-run on yamato so the results appear here?

@sophiaaar  So the tests failed, but for a very weird reason: they don't seem to be reproducing the GPU sorting bug (which makes some systems spawn only 1 particle).

In the last year, I have never known that GPU sorting bug to not reproduce on OSX: what machine are the Yamato OSX tests running on?

**Comment by VladNeykov** [comment]
Ended up updating the ref images with the mac mini results. Will need to be replaced once the GPU sorting bug is fixed, made a note on the FB case.

Yamato tests passed:
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/vfx%2Ftests%2Fadd-urp-osx-coverage/.yamato%2Fupm-ci-vfx_lwrp.yml%23VFX_LWRP_OSX_playmode_trunk/399968/job
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/vfx%2Ftests%2Fadd-urp-osx-coverage/.yamato%2Fupm-ci-vfx_lwrp.yml%23VFX_LWRP_OSX_Standalone_trunk/399969/job

**Pull request merged**
