### PR TITLE
Fix specular fp16 overflow on Switch

### PR DESCRIPTION
**Pull request by unity-cwells**
### Purpose of this PR
Light reflecting off perfectly or near perfectly smooth surfaces can result in a specular term near/above  
the maximum fp16 value. This can result in visible artifacts when post-process effects (like bloom) propagate this value as +inf. A fix for this issue already exists for mobile platforms and this PR just extends the fix to cover Switch.

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [x] C# and shader warnings
- Other: Build and ran the lwrp template project for Switch and Windows Standalone

**Automated Tests**: 

katana_build_result

https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=lw%2Ffix-switch-fp16-overflow&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

---
### Overall Product Risks
**Technical Risk**:  Low

**Halo Effect**: None

---

### CODE REVIEW

**Comment by phi-lira** [comment]
This PR seems to be already merged in master? When did that happen?

**Comment by unity-cwells** [comment]
As far as I can tell this PR hasn't been merged into master yet. I don't see the changes to Lighting.hlsl on master and it still shows as 'Merging is blocked'.

**Comment by phi-lira** [comment]
LGTM.  
Maybe I confused it with something else, but I could swear I just merged master to my branch and this change was there.

**Comment by phi-lira** [comment]
should we backport this to 2019.2?

**Comment by unity-cwells** [comment]
That would be ideal. Would you like me to do the backport?

**Comment by phi-lira** [comment]
If you create the backport PR (branch off from release/2019.2) we will take it.

**Pull request merged**
