### PR TITLE
Surface Shader Graph

### PR DESCRIPTION
**Pull request by gistofj**
This change adds a Surface Shader master node to Shader Graph for Universal Render Pipeline.

The Surface Shader Master is intended to be a master node which supports stylized shader graphs like a Unlit Master, will all of the functionality and power of a PBR Master. Surface Shader Master does not provide any intrinsic lighting or shadowing (ala Unlit Master), but does provide access to the Unity libraries which do provide lighting and shading (ala PBR Master), without any keywords that disable functionality.

The goal is to provide a master node from which creators are free to create the effects and appearances they want, without limitation imposed by intrinsic behaviors.

I was inspired to submit this after read/watching the following content (provided by Unity) because in all cases the author/speaker lamented the lack of functionality provided by Shader Graph. The same lack of functionality I was being personally annoyed by as well.

* https://www.youtube.com/watch?v=DOLE4nrK97g
* https://blogs.unity3d.com/2019/07/31/custom-lighting-in-shader-graph-expanding-your-graphs-in-2019/
* https://connect.unity.com/p/zelda-inspired-toon-shading-in-shadergraph

Below are a couple of screen captures I've taken of the new graph in action. The first image is a capture of a graph using the new node (I've chose to implement something akin to the links above). The second image is a capture of the Game View using a material created by the graph in the previous image.

**Graph View**
image

**Game View** (2 capsules + 1 cube)
image

I have been wrestling with the name because naming things is difficult. Originally, I named it "stylized master" because my goal was to support a mode stylized look. However, it was pointed out to me that it could support more than just "stylized" shaders -- and it was more like a surface shader for Shader Graph. Hence the current name of "Surface Shader Master". I am 100% open to better names.

Other names I've though of (and discarded):
 - **Basic Graph**: because while it is basic, newer users might assume it is the easiest one to start with (and it is quite the opposite).
 - **Simple Graph**: see _Basic Graph_.
 - **Customizable Graph**: because aren't _all_ grpahs customizable? I mean, that is the point.

---
Caveats:
- My first PR for anything Unity related, so I am sure I've done something wrong code wise. I'll be happy to conform the changes as needed, just let me know in the PR comments / review.
- I have been unsuccessful in getting any kind of testing, or even local builds (outside of Unity itself) working. I have been able to build and use the new master node using Unity 2019.3b8
---
Leaving the lengthy checklist of what to do when submitting a PR below, to be completed after I know if there is any desire for this kind of change.

### Checklist for PR maker
- Have you added a Label? : HDRP, Universal, ShaderGraph etc...
- Have you added a label for backport (if needed)? : need-backport-2019.3  .  When the PR is backported the label will be change ton backported-2019.3
- Have you added a changelog? Each package have a changelog.
- Have you updated or added the documentation for you PR? When property name is changed, when a feature behavior is change, when adding a new features, think to update the documentation in the same PR.
- Have you added a graphic test for your PR (if needed)? When adding new feature or discovering a bug that isn't cover by a test, please add a graphic test
---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (suppress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: manually compiled and executed the code inside Unity, including created an example graph and used it to create a material and applied that material in a scene.

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by gistofj** [comment]
Alex Lindman of "Custom Lighting in Shader Graph: Expanding your graphs in 2019" assigned to review my code change ?.. 😮 <faints />

**Comment by alindmanUnity** [comment]
Hi there! Thanks so much for this PR but we can't accept this at the moment -- we've been hard at work re-writing the entire generation API and this would become immediately incompatible. We've opened the PR here #4940 if you'd like to see what we've done so far. This is part of a larger overhaul on the Shader Graph master nodes and generation system, and we plan to add this same functionality in future versions after the overhaul is complete. 
I do encourage you to share this around on places like the forums or the user discord if people want to create local workarounds for older versions of the package, but the team can't take on the technical debt of upgrading and maintaining another master node at this time. :)

**Comment by gistofj** [comment]
> but the team can't take on the technical debt of upgrading and maintaining another master node at this time. :)

Thanks for the response. Completely understandable. As a professional software engineer I've been in a similar situation myself. :) 

> We've opened the PR here #4940 if you'd like to see what we've done so far.

Very interesting, and obvious as to why there's no reasonable way to accept this PR as-is.

Out of curiosity, is there any plan to make Shader Graph's master node collection extensible by third-parties without having to contribute to Unity and thus adding to the team's technical debt? Looks like the refactor makes `AbstractMaterialNode` the base for all master nodes, but it (and many other types) are still `internal`. The good new is that `IMasterNode` is public, so there's hope yet!

It would be fantastic to see at least `public interface` types exposed such that any party that implemented them correctly could contribute to the Unity community via free assets.

Ironically, this all started with me reading your (@alindmanUnity) blog on Shader Graph lighting and its example of how to make a "toon shader", and then realizing it wasn't possible to get proper shadows unless I used the PBR master, and then it looked horrible. I found a number of commentors suggesting leaving albedo=0 and writing call color data to the emission slot, but felt we could do better. Hopefully in the near future we can! (I'll be happy to resubmit this PR, refactored for the updated code base, if/when asked).

Thanks again

**Comment by alindmanUnity** [comment]
We are a ways out from being able to have a publicly supported open API, but that is the direction and dream that we're moving towards. Slowly but surely c:

**Comment by xCyborg** [comment]
This is so valuable as a Master Node, we could definitely use a note somewhere between Unlit and PBR as a surface node, especially with custom functions.
Glad to know you intend to add this functionality in the future.

**Pull request closed without merging**
