### PR TITLE
Rename PhysicallyBasedSkySettings to PhysicallyBasedSky

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Fulfill the request of @Chman

---
### Testing status
**Katana Tests**: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=HDRP%2Frename-pbr-sky-again&automation-tools_branch=master&unity_branch=trunk

### CODE REVIEW

**Comment by EvgeniiG** [comment]
Tried running tests locally with the latest trunk, and everything falls apart:

image

**Comment by sebastienlagarde** [comment]
Plenty of failure are due to the deprecation of the procedural sky. I have update the test project and merged hdrp/staging into your PR and relaunched katana

**Comment by EvgeniiG** [comment]
OK, makes sense, thanks. I will try running tests locally again.

**Comment by EvgeniiG** [comment]
I guess I need to update C++ again? I am on yesterday's version.

image

**Comment by EvgeniiG** [comment]
Merge introduced conflicts, I re-queued Katana.

**Comment by EvgeniiG** [comment]
OK, the merge did not change the error pattern, so either everything is broken or I need to update C++ again.

**Comment by sebastienlagarde** [comment]
yes, the trunk merge queue batch with all the C++ PR for HDRP out of preview have landed Thursday noon. you need to get trunk again (I send a message on slack).

Few hours in HDRP land is severals years behind :)

**Pull request merged**
