### PR TITLE
ShaderGraph Tests in LWRP

### PR DESCRIPTION
**Pull request by spaztronaut**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Adds some ShaderGraph tests to the LWRP Test Project
Modifies LWGraphicsTest.cs to check for LWRP Test Settings or SGLW Test Settings

---
### Release Notes
Please add any useful notes about the feature/fix that might be helpful for others.
3 test scenes and reference images added for Windows + DX11:
1. Unlit (includes alpha clip)
2. Lit (includes alpha clip)
3. Vertex offsets with ShaderGraph in LWRP

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- Other: 

**Automated Tests**: What did you setup?

Any test projects to go with this to help reviewers?
TestProjects/LWGraphicsTest

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Low

**Halo Effect**: None, Low, Medium, High?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by phi-lira** [comment]
what about mac?

**Comment by spaztronaut** [comment]
there's a test that fails (split screen scene) but that also fails on master

**Comment by phi-lira** [comment]
What's the status on this PR?

**Comment by phi-lira** [comment]
Is this PR still planned to be worked on/merged?

**Comment by spaztronaut** [comment]
i believe so. i will talk with zack  and landon next week about getting these tests updated and resolving any conflicts

**Comment by soraryu** [comment]
Note that ShaderGraph URP tests now live in a separate folder; see 
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4675
for why & where. @sophiaaar

**Comment by ellioman** [comment]
What's the status of this PR?

**Pull request closed without merging**
