### PR TITLE
Better (not hardcoded) stencil handling in VFX

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
This avoids the hardcoded stencil values for the distortion and gbuffer pass in VFX graph.

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
> I realized some template should also be replaced : https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.high-definition/Editor/VFXGraph/Shaders/Templates/Mesh/PassGBuffer.template
> You can look for all "Stencil" declaration in "VFXGraph/Shaders/Templates"

Oh right, odd, I didn't see those files in VAX, will do Monday

**Comment by FrancescoC-unity** [comment]
Yeah can confirm Visual Assist don't find those files, weird :/ Anyhow, updated them now

**Comment by PaulDemeulenaere** [comment]
> Yeah can confirm Visual Assist don't find those files, weird :/ Anyhow, updated them now

I guess VAssistX does a kind of "distinct" based on filename while listing them.

**Comment by PaulDemeulenaere** [comment]
There are also two "PassDistorsion" templates (it should be factorized at some point), you missed this one : https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.high-definition/Editor/VFXGraph/Shaders/Templates/Mesh/PassDistortion.template

**Comment by FrancescoC-unity** [comment]
> There are also two "PassDistorsion" templates (it should be factorized at some point), you missed this one : https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.high-definition/Editor/VFXGraph/Shaders/Templates/Mesh/PassDistortion.template

Uhm no, that one I upated already :/

**Comment by PaulDemeulenaere** [comment]
> > There are also two "PassDistorsion" templates (it should be factorized at some point), you missed this one : https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.high-definition/Editor/VFXGraph/Shaders/Templates/Mesh/PassDistortion.template
> 
> Uhm no, that one I updated already :/

Ah yes, sorry, I misread the changes.

**Pull request merged**
