### PR TITLE
Adding Linux CI pipelines to SRP TestProjects

### PR DESCRIPTION
**Pull request by markitect**
### Purpose of this PR
Added Linux support to the TestProjects.  This involved modifying yamato scripts to add Linux pipelines, adding reference images for OpenGLCore and Vulkan (when possible), and fixing a casing issue when building asset bundles for reference images for running in a player.  Also added custom editor command line static methods to build Linux players for test configurations.

---
### Release Notes
I did not add Linux support for hdrp test projects since there are blocking issues.  I did still added support for VFX main since I didn't realize that depended on hdrp, but only for Vulkan

---
### Testing status
**Yamato Tests**: All pipelines have been verified to work - only real issues remain, mainly with Vulkan tests (which are expected but need to be documented)

**Manual Tests**: What did you do?
- [X] Opened test project + Run graphic tests locally
- [X] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**:  Added Linux Support for OpenGLCore and Vulkan to universal, postprocessing, shadergraph, vfx_lwrp, and vfxmain yamato pipelines.

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/linux-ci

---
### Overall Product Risks
**Technical Risk**: None only touched Linux

**Halo Effect**: None only touched Linux

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sophiaaar** [comment]
Is it intended that the Linux pipelines won't run as part of the "All CI" shortcuts?

**Comment by markitect** [comment]
I wasn't going to add them to All CI until this landed and was stable.

**Comment by markitect** [comment]
Linux editor playmode tests are blocked from passing by https://fogbugz.unity3d.com/f/cases/1187515/

**Comment by sophiaaar** [comment]
I'm still happy to merge this since the PR is to set up the Linux pipelines

**Pull request merged**
