### PR TITLE
Fix artifacts on rectangular lights

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Same PR again: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4597

### CODE REVIEW

**Comment by EvgeniiG** [comment]
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Ffix-rect-lights/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP/520431/job

**Comment by EvgeniiG** [comment]
Playmode tests failed, but I am not sure what this implies since I am only aware of edit mode tests.

**Comment by EvgeniiG** [comment]
Looks like there is a decal-related issue...

**Comment by sebastienlagarde** [comment]
Error on decal come from bad verison of HDRP/Staging, I merged HDRP/staging again

**Comment by sebastienlagarde** [comment]
Update all screenshors. running yamato again

**Pull request merged**
