### PR TITLE
[8.x.x Backport] Fix fog density returning zero with an Unlit Master Node

### PR DESCRIPTION
**Pull request by Nightmask3**
Purpose of this PR
Backport of #6008

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/8.x.x%252Fsg%252Ffix-fog-density-returning-zero

### CODE REVIEW

**Comment by Nightmask3** [comment]
> Looks good except you're missing a changelog change :)

Thanks for the reminder! Just committed it now.

**Comment by LandonTownsendUnity** [comment]
You can remove qa-gfx-bellevue since I already reviewed it.

**Comment by LandonTownsendUnity** [comment]
Did you mean to remove "fix changelog" from the changelog?

**Comment by Nightmask3** [comment]
> Did you mean to remove "fix changelog" from the changelog?

Yeah it seemed like placeholder text that I could replace, though I could be mistaken?
Sorry I didn't mean to tag you again, I just wanted @ellioman to get a notification that I'd pushed the requested change, I need to find out how to notify people individually as opposed to everyone on the review. 😅

**Pull request merged**
