### PR TITLE
Fp16 fix error calculation

### PR DESCRIPTION
**Pull request by victor-unity**
### Purpose of this PR
On iOS and MacOs, when using fp16, the specular lighting values can go wrong because of precision issue. Added a saturate to a value that should be between 0 and 1 anyway, but if it goes beyond one, then some results can be wrong in the rest of the calculation.
---
---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: Low

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by kaychang-unity** [comment]
FYI I found this old blog post about saturate(x) vs max(0, x): https://nyahoon.com/blog-en/590
I wonder if there is still a perf diff on mobile GPUs?

**Comment by sebastienlagarde** [comment]
would suggets to also add a comment (i will do it), otherwise futher people could remove it

**Comment by sebastienlagarde** [comment]
> FYI I found this old blog post about saturate(x) vs max(0, x): https://nyahoon.com/blog-en/590
> But you want min(1, x), probably saturate() is faster then?

saturate is free, min and max are one instruction.

**Comment by sebastienlagarde** [comment]
>but if it goes beyond one,

 don't understand in which case roughness could be beyond 1. With current set of shader it shouldn't be possible, or people do bad thing in shader graph and input wrong value for roughness? 
It is a bit like NaN, yes we can provide NaN killer but ultimately it doesn't solve the issue of the wrong input from material that cause it and that certainly don't produce the result you want. Here same thing, I have the feeling that we hide the problem to the users instead of helping him to find that he have a problem with a Material.

Thought?

**Comment by victor-unity** [comment]
Holà, 
I have tried to narrow down the cause of the bug, it is weird because if I replace a2 by 1.0001 for instance I do not see any problem. I have tried to write a specific shader with only this function, but I could not reproduce the bug. Moving the saturate later in the code works too : 
`real2 D = real2(saturate(a2), (s * s)); `
It seems that Filament has a similar issue (https://google.github.io/filament/Filament.md.html cf D_GGX function) ; so basically there is a lack of precision around 1 in fp16, and doing a computation like  :
 `1 - a_number_close_to_one `
 can lead to zero instead of a small number. 
But in our case, even if a2==0 I do not see the bug.
I do not understand how roughness can be higher than 1, I will  re-check the unpack functions. 
and continue to investigate...

**Comment by sebastienlagarde** [comment]
>Or as KayChang suggested we modify codegen in order to store real as float.
>What do you think ?

What does this imply? I mean what will be the generated code in this case?

>For iOS, one solution would be to use only floats in the hlsl LightData structs. That solution fixes the >bug we saw here.
That's of course work, Kaychang changed it to make it faster for switch, so it mean we just revert the optimization. So Let's see what's the above solution imply, otherwise I fine with changing to float.

**Comment by sebastienlagarde** [comment]
I am closing this PR for now, as it require a bit more work. Can re-open the PR or do another one in another form later (just to clean pull request list)

**Pull request closed without merging**
