### PR TITLE
Allow custom spot angle for shadow map rendering 

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
### Purpose of this PR
This adds an option to specify a custom spot angle for the shadow map rendering sake. 

---
### Release Notes
Allow to specify a custom spot angle.

Can't access katana for now :-( Will launch one as soon as I get it loading.

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
Sadly the sampler clamps at edges instead of border, so that will lead to some artifacts, but I am told we don't support border color on samplers.

**Comment by sebastienlagarde** [comment]
Please @TomasKiniulis have a look :). (Even if I merged the PR)

**Comment by sebastienlagarde** [comment]
@FrancescoC-unity Please update the shadow manual

**Comment by TomasKiniulis** [comment]
Custom spot angle for shadow map rendering works without any issues observed, custom shadow angles properly decouples the cone that is used to produce shadows vs the cone used for the light. 
https://confluence.hq.unity3d.com/display/HDRP/Custom+spot+angle+for+shadow+map+rendering

**Pull request merged**
