### PR TITLE
Use non-experimental UIElements

### PR DESCRIPTION
**Pull request by patrickfournier**
### Purpose of this PR
Port the package to the non-experimental UIElements API.

Non-experimental UIElements API is in PR https://ono.unity3d.com/unity/unity/pull-request/76476/_/ui-elements/19.1-staging.

The plan is to make experimental and non-experimental APIs available together for a short while, before removing the experimental API (scheduled to happen before the 2019.1 cutoff).

This PR must land after the introduction of non-experimental API, but before the removal of experimental API.

---
### Release Notes
Please add any useful notes about the feature/fix that might be helpful for others.

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: Open Shader graph examples in Unity. Checked the UI for obviously misplaced elements. Verified the shaders work.

**Automated Tests**: No new tests needed.

Any test projects to go with this to help reviewers? No

---
### Overall Product Risks
**Technical Risk**: Low to Medium. This is mainly trivial API changes. The riskiest changes are the input field refactor (every input is now inside a container field) and the default USS style adjustments which were done to match Unity style. These adjustments may impact UI element positioning.

**Halo Effect**: Low. Only UI.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by zadi0648** [comment]
blackboardarrowmissing1
Expand / Collapse arrows seem to be missing from the blackboard

**Comment by zadi0648** [comment]
texturefieldchange0
Not a big deal, but for texture properties only it appears the input field has a smaller image icon and the text is lowered and not centered.

**Comment by zadi0648** [comment]
defaultsmissingafter0
This one also really needs to be resolved; only the first default value input for nodes are displayed (although this changes when minimizing / maximizing the node preview)

**Comment by zadi0648** [comment]
inputfeildsmaller0
When the default input field is a vector 1 type it is now too small

**Comment by zadi0648** [comment]
master2
Although in another project the nodes do this.
- The Color default ports are very stretched out
- There is a weird red line between the default ports and the port
This happened in one project that had pre-existing shader graphs. I can't figure out the difference otherwise; they are using the same unity & srp branch.

**Comment by jfparadis18** [comment]
> blackboardarrowmissing1
> Expand / Collapse arrows seem to be missing from the blackboard

The arrow is fixed in two trunk CS : 3a3e162f1dbc and 749312a9e3e3.
In fact, you should use the following branch : uielements/graphview-fixes to have both fixes.

**Comment by jfparadis18** [comment]
> defaultsmissingafter0
> 
> This one also really needs to be resolved; only the first default value input for nodes are displayed (although this changes when minimizing / maximizing the node preview)

The fix for this problem is in : 981b910cb

**Comment by jfparadis18** [comment]
> texturefieldchange0
> 
> Not a big deal, but for texture properties only it appears the input field has a smaller image icon and the text is lowered and not centered.

The fix for this problem is in a91cdd330

**Comment by jfparadis18** [comment]
> inputfeildsmaller0
> 
> When the default input field is a vector 1 type it is now too small

The fix for this is in 5e15a200f

**Comment by pbbastian** [comment]
@patrickfournier It looks like the latest merge went very wrong, and now this PR contains lots of unrelated changes. Please fix :) I suggest rolling the branch back to before your local merge commit (`8515a45`), and then force pushing.

**Comment by patrickfournier** [comment]
@pbbastian I fixed the PR. There is a sconflict to resolve, but I am not sure if you need to use UnityEngine.Experimental.Rendering; or UnityEngine.Rendering; or both?

**Comment by zadi0648** [comment]
pinkblueborder
The preview has a pink & blue border (this is with trunk and not the designated Unity build)

**Comment by zadi0648** [comment]
Ask me on slack if you want the Shader Graph file that I could not open

**Comment by patrickfournier** [comment]
@zadi0648 My last commit should enable you to open the shadergraph file.

**Comment by patrickfournier** [comment]
@Katstodian No tooltip and this does not requires a changelog entry.

**Comment by patrickfournier** [comment]
> The preview has a pink & blue border (this is with trunk and not the designated Unity build)

UIElements now supports shorthands (like `border-width`) which were previously ignored. I presume you don't want any border here so I edited the USS style for these elements.

**Comment by patrickfournier** [comment]
Please use Ono branch `uielements/graphview-fixes` to have the fix for the missing arrow images.

**Comment by Kink3d** [comment]
@pbbastian Since this is merged to trunk are we going to merge it now?

**Comment by pbbastian** [comment]
Running katana here: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=uielements-out-of-exp&automation-tools_branch=add-platform-filter&unity_branch=trunk

**Comment by pbbastian** [comment]
Katana only fails on a test known to be failing on master.

**Pull request merged**
