### PR TITLE
[LW][XR] Fix FB#1142952 - Vulkan renders only to one eye with single-pass instancing mode 

### PR DESCRIPTION
**Pull request by mikesfbay**
### Purpose of this PR

Fix for shaders on Vulkan not setup for stereo instancing. 
Fix for stereo matrices and vertex input not setup on Vulkan.

---
### Release Notes

[case 1142952](https://fogbugz.unity3d.com/f/cases/1142952/)
---
### Testing status
**Katana Tests**:  [katana](https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=lw%2Fxr-vulkan-spi-fixes&automation-tools_branch=master&unity_branch=trunk) mostly passed (same as master after latest merge)

QA @ryanhy-unity tested on XR platforms.

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [x ] C# and shader warnings 
- Other: 

Tested locally on Oculus HMD with OpenVR and Vulkan in standalone player

**Automated Tests**: 

---
### Overall Product Risks
This change only affects XR and Vulkan only.
**Technical Risk**: Low

**Halo Effect**: None

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by Katstodian** [comment]
Hi - can you please add a changelog entry and ping GFX-Docs for review on that? :)

**Comment by phi-lira** [comment]
@mikesfbay please add docs so we can merge this.

**Comment by mikesfbay** [comment]
@phi-lira @Katstodian I've updated the docs with the changes.

**Comment by mikesfbay** [comment]
@phi-lira docs approved, please merge, thanks

**Comment by phi-lira** [comment]
@mikesfbay is katana on SRP green?

**Comment by phi-lira** [comment]
Please also let me know if this is meant to be backported to 2019.2 and/or 2019.1 by adding `needs-backport-2019.` labels.

**Comment by mikesfbay** [comment]
@phi-lira katana passed, results same as master after last merge.
Trunk vulkan backport changes landed in 2019.2 staging, thus this would backport to 19.2

**Pull request merged**
