### PR TITLE
Exclude objects that tag the stencil with a specific bit from TAA [2019.2]

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
### Purpose of this PR
This PR allows part of the frame to not execute TAA, but go straight through with just the unjittered sample of the scene color. 

The client for this is particles, so the tagging of the stencil will need to happen on VFX side. 

I know reviewers are not in this week, but I thought of opening the PR anyway for book keeping 🙂 

---
### Testing status
**Katana Tests**:  https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?automation-tools_branch=master&ScriptableRenderLoop_branch=HDRP%2Fexclude-from-taa&unity_branch=trunk [ Green ] 

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- Other: 

---
### Overall Product Risks
**Technical Risk**:  Low

**Halo Effect**: Low

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
Closing this to port it to current master. The merge messed things up.

**Comment by FrancescoC-unity** [comment]
Actually TAA is broken in master atm, but a fix is in the pipe. Re-opening this PR as I might not need to do the manual port.

**Comment by sebastienlagarde** [comment]
Ok, so need to merge with master and relaunch test I guess :)

**Comment by sebastienlagarde** [comment]
poking @julienf-unity .  We need to discuss this as it was not clear they want to use this solution.

**Comment by FrancescoC-unity** [comment]
Closed as ported to current status of master/staging in https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/3963

**Pull request closed without merging**
