### PR TITLE
Lw/speedtree shaders 2019.1

### PR DESCRIPTION
**Pull request by russoh**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Backport for https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2857

This PR requires the following trunk PR to be merged first to support the functionality:
https://ono.unity3d.com/unity/unity/pull-request/83525/_/2019.1/graphics/srp-speedtree

The original PR branches (engine and SRP) are still in review, so this backport will be gated by those landing first. This PR will be the last one to be merged, ideally synchronized with the engine backport if possible.

---
### Release Notes
Please add any useful notes about the feature/fix that might be helpful for others.

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
Have tested SpeedTree 7 and 8 test assets at all LODs, with all LOD options.

**Automated Tests**: What did you setup?

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Low

**Halo Effect**: None, Low, Medium, High?
Low

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by russoh** [comment]
Builds are here:
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=lw%2Fspeedtree-shaders-2019.1&automation-tools_branch=master&unity_branch=2019.1%2Fgraphics%2Fsrp-speedtree

**Comment by sebastienlagarde** [comment]
Hi, is there a reasons for the High Priority tag ? Seems like this PR is old now.

**Comment by russoh** [comment]
> Hi, is there a reasons for the High Priority tag ? Seems like this PR is old now.

It was intended to be synced with the release of 2019.1 and lwrp, and was being urged to be ready in time. In practice, getting testing feedback has taken a lot longer than needed for this to happen, and it will likely end up in a later package release.

**Comment by russoh** [comment]
Tests: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=lw%2Fspeedtree-shaders-2019.1&automation-tools_branch=master&unity_branch=2019.1%2Fstaging&sort=1-asc

**Comment by russoh** [comment]
All tests are green, ready to merge.

**Pull request merged**
