### PR TITLE
Stack lit2

### PR DESCRIPTION
**Pull request by slunity**
This PR add specular occlusion support to Lit shader and StackLit shader based on Spherical Pivot Distribution from Jonathan Dupuy

### CODE REVIEW

**Comment by laurenth-unity** [comment]
I got an issue when using the object space normal / bent normal map mode.

**Comment by slunity** [comment]
This is a problem in the Lit material. 
Seems the _BentNormalMapOS property is missing in LitProperties.hlsl, 
(ie no  "PROP_DECL_TEX2D(_BentNormalMapOS);"  ) 
but this problem is there in master and staging too.

**Comment by sebastienlagarde** [comment]
yes, it still plan

**Comment by sebastienlagarde** [comment]
reopen, close by mistake

**Pull request closed without merging**
