### PR TITLE
Fix for "Show Generated Code"

### PR DESCRIPTION
**Pull request by martint-unity**
Fix for open generated shader when external editor not set. Also tested on Mac.

### CODE REVIEW

**Comment by martint-unity** [comment]
Not working yet on MAC

**Comment by zadi0648** [comment]
On Windows, works well. Works with different editors, simple graphs, complex graphs, graphs with shader groups, ect.
On OsX, there is no error like in trunk but it opens up the external editor without opening up the generated shader in the external editor. Tried this with sublime text, Visual Studio, and TextEdit.

**Comment by zadi0648** [comment]
Approving. Treating the OsX case as a separate bug, here is the bug case: https://fogbugz.unity3d.com/f/cases/1079798/

**Comment by pbbastian** [comment]
Needs change log change

**Comment by martint-unity** [comment]
Added change log
Merged with latest master
Running Katana right now.

**Comment by martint-unity** [comment]
@pbbastian 
Test are successful
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=sg%2Ffix-open-generated-shader-when-external-editor-not-set&automation-tools_branch=add-platform-filter&unity_branch=trunk

**Pull request merged**
