### PR TITLE
LWRP + XR will now use HDR if it is enabled.

### PR DESCRIPTION
**Pull request by brandon-unity3d**
### Purpose of this PR
HDR color formats are currently not used when HDR is enabled and using LWRP + XR.
This PR addresses that issue.
---
### Release Notes
An HDR color format will be used when HDR is enabled for XR and LWRP.

---
### Testing status
**Katana Tests**: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?automation-tools_branch=add-platform-filter&ScriptableRenderLoop_branch=xr%2Fgfx%2Flwrp%2Fhdr-fix&unity_branch=2019.1%2Fstaging

**Manual Tests**: What did you do?
I tested with the editor and RenderDoc.

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Low

**Halo Effect**: None, Low, Medium, High?
Low

---

### CODE REVIEW

**Comment by phi-lira** [comment]
Hey brandon, thanks for looking at this. Do you know if there's any other setting apart from HDR that the VR eye texture descriptor doesn't set? e.g, SRGB texture etc?

**Comment by phi-lira** [comment]
Please also add releaset notes to LWRP CHANGELOG.md

**Comment by brandon-unity3d** [comment]
> Hey brandon, thanks for looking at this. Do you know if there's any other setting apart from HDR that the VR eye texture descriptor doesn't set? e.g, SRGB texture etc?

@phi-lira Fixed in d03773113d2b93373aec3704e5cefbe91fa74393

**Comment by brandon-unity3d** [comment]
> Please also add releaset notes to LWRP CHANGELOG.md

@phi-lira Fixed in 161dd9f6617c1aa9010e0b1789ad9a8d56e70135

**Comment by phi-lira** [comment]
Adding @Katstodian for changelog review.

**Comment by brandon-unity3d** [comment]
@phi-lira I fixed the conflict.  Can you merge this now?  Thanks!

**Pull request merged**
