### PR TITLE
Universal Improvements

### PR DESCRIPTION
**Pull request by phi-lira**
### Purpose of this PR
 - Optimized Load/Store for the ColorGrading LUT pass. Not it doesn't load contents of both color and depth.
 - Moved copy depth pass to after skybox. This prevents to switch render target in between opaques and skybox.
 - Added more profiler markers in the ScriptableRenderer
 - Added support to be able to bind the current active render target and to bind to none as well. 
 - Submit context work after shadow maps and main rendering block.

Testing: Not high risk PR. There's no new features only improvements. Adding QA to figure out if there's no perf regression. Possible check boat attack on android and iOS and it should be fine imo.

---
### Release Notes
 Added

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: Low.

**Halo Effect**: Low.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by phi-lira** [comment]
@Wilfrid-Unity you could already use it but the ScriptableRenderer was not listening to it.

**Comment by sebastienlagarde** [comment]
Poking. Don't you want to merge all the improvement of this PR ?

**Comment by cinight** [comment]
I've already requested help from mobile team to run performance testing on boat attack on Android and iOS. So now I'm waiting for the test result from mobile team.

**Comment by ellioman** [comment]
Closing because work already merged

**Pull request closed without merging**
