### PR TITLE
Add an option to enable reprojection for volumetrics

### PR DESCRIPTION
**Pull request by EvgeniiG**

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Katana?

**Comment by EvgeniiG** [comment]
Didn't seem necessary, as I simply added a checkbox to the UI.

I started Katana now: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=bugfix_volumetrics&automation-tools_branch=add-platform-filter&unity_branch=trunk

**Comment by sebastienlagarde** [comment]
It is mandatory to have katana test green for anything going to master. 

(For small change we can use HDRP/staging but as we wait for GitHub reply to know what is happening on it we try to avoid it for now)

**Comment by sebastienlagarde** [comment]
Katana is green: https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=bugfix_volumetrics&automation-tools_branch=add-platform-filter&unity_branch=trunk

**Pull request merged**
