### PR TITLE
[VFX] Merge vfx/staging

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
### Important
~This merge will update minimal unity version from **2020.10a3 to 2020.10a8** !~
Actually, minimal version has been updated to a11 on master.

### Purpose of this PR
Last merge of `vfx/staging` was almost a month ago : https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4662

_Added :_ 
- Some editor test
- Custom Inspector for Spawn context, delay settings are more user friendly.
- Quick Expose Property : Holding Alt + Release Click in an Empty space while making property edges creates a new exposed property of corresponding type with current slot value.
- Octagon & Triangle support for planar distortion output
- Custom Z axis option for strip output

_Fixed :_ 
- Selection Pass for Universal and High Definition Render Pipeline **<= this change creates a conflict with https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4707, that is why it would be appropriate to merge `vfx/staging` into `master`**
- Copy/Paste not deserializing correctly for Particle Strip data
- WorldPosition, AbsoluteWorldPosition & ScreenPos in shadergraph integration
- Optimize VFXAssetEditor when externalize is activated
- TransformVector|Position|Direction & DistanceToSphere|Plane|Line have now spaceable outputs
- Filter out motion vector output for lower resolution & after post-process render passes [Case 1192932] (https://issuetracker.unity3d.com/product/unity/issues/guid/1192932/)

**Yamato**: https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/vfx%252Fstaging

### CODE REVIEW

**Comment by julienf-unity** [comment]
I would like my fixes on shader graph integration to be in this batch (PR probably tomorrow).
Also I dont see any recompilation of vfx. This should always be the last PR before a merge to master (if any)

**Comment by PaulDemeulenaere** [comment]
Ok, I agree, it would be nice to have your shader graph integration fix.
The merge in master can wait until the end of the week (or beginning of the
next week if Yamato is busy), I was expecting a few additional changes
before vfx recompilation.

I was also considering squash/merge this PR (tooltip) :
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4805
and handle the backport in vfx/staging-2019.3 branch.

Le mar. 22 oct. 2019 à 21:05, julienf-unity <notifications@github.com> a
écrit :

**Comment by julienf-unity** [comment]
Ready to be merged as soon as yamato is green

**Comment by PaulDemeulenaere** [comment]
Two failures on last yamato abv run : 
**HDRP on Windows64_DX11_playmode XR :** 
- 1303_StackLitSG_Testers
- 2106_GI_EmissionSG
See : https://yamato-artifactviewer.prd.cds.internal.unity3d.com/58bb3627-5d60-4ae5-8b11-9102837bfbde%2Flogs%2FTestProjects%2FHDRP_Tests%2Fupm-ci~%2Ftest-results/TestReportV1.html
**HDRP on Windows64_DX11_playmode**
- 1303_StackLitSG_Testers
- 2106_GI_EmissionSG
See : https://yamato-artifactviewer.prd.cds.internal.unity3d.com/b3f9313b-6da6-4194-9c98-b6ed4d404ac5%2Flogs%2FTestProjects%2FHDRP_Tests%2Fupm-ci~%2Ftest-results/TestReportV1.html

**Comment by PaulDemeulenaere** [comment]
- Merge in release/2019.3 of these changes has been done a week ago : eb2c3200a702027d9ebda8ee19d6476953a62cbf
- I'm still waiting for the merge of this batch to provide a minimal change to : https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4707
- Ads package causing an issue in test framework is still there but the fix is in progress : https://unity.slack.com/archives/C0JHA6J4C/p1572605124210000

**Comment by PaulDemeulenaere** [comment]
All green expect HDRP Play Mode DX11 : 
image

The failure is due to `2103_GI_BakeMixed` :
**Expected**
image

**Actual**
image
_Look at green bottom left corner_ ⬆️ 

See : https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/vfx%252Fstaging/.yamato%252Fupm-ci-hdrp.yml%2523HDRP_Windows64_DX11_playmode_trunk/751531/job

**Comment by PaulDemeulenaere** [comment]
There is the same failure with GI on master, the involved change is probably in trunk : 
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/master/.yamato%252Fupm-ci-hdrp.yml%2523HDRP_Windows64_DX11_playmode_trunk/754804/job

**Pull request merged**
