### PR TITLE
Hdrp/pt8

### PR DESCRIPTION
**Pull request by eturquin**
* Added finer light selection oracle for sampling in path tracing.
* Changed path tracing test reference image following the oracle change.
* Added SSS support in path tracing.
* Fixed issue with resolution change in the test framework.
* Code refactor.

BEWARE: First commit of pt8 is actually:
Added finer estimates of lights during global pdf computation.  be051b5

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
@remi-chapelain Path trace test merged in pt8. 
@eturquin could you launch the DXR test locally with those new tests, just to be sure that everything still green. Thanks

**Comment by eturquin** [comment]
> @eturquin could you launch the DXR test locally with those new tests, just to be sure that everything still green. Thanks

All tests are good.

**Comment by eturquin** [comment]
All tests but the 5001 path tracing one are green. For this one, we need this PR:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/6174

**Comment by eturquin** [comment]
All tests are now green, merge is a go! :)

**Pull request merged**
