### PR TITLE
Fixed XR Multiview with URP Shader Graph

### PR DESCRIPTION
**Pull request by thomas-zeng**
### Checklist for PR maker
---
### Purpose of this PR
This PR fixed XR multiview failure with URP Shader Graph, fogbugz case:
https://fogbugz.unity3d.com/f/cases/1195463

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
QA: Need to test this PR on Oculus Go.

### CODE REVIEW

**Comment by soraryu** [comment]
@DennisDeRykeUnity I think the MSAA breakage might be what I was already pointing out here:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4788#issuecomment-545195183
(the small dot pattern when MSAA is enabled)

**Comment by ROBYER1** [comment]
> I tested urp/xr/fix-shadergraph-multiview with the Unity Editor built from 2019.3/staging changeset f7cbc86d849f on Oculus Go using the repro project from case 1195463 in MultiView stereo mode.
> 
> The SpeedTree materials were hot pink but to fix this select the BroadLeaf Mobile prefab, go to the Materials tab in Inspector, and click Regenerate Materials.
> 
> I see only two OPENGL messages in LogCat, not a constant stream of them.
> 
> Scene lighting is comparable to the everythingisfine.png in the Fogbugz case.
> 
> I notice no warping in either eye.
> 
> I saw the water and UI after opening each ShaderGraph material in the ShaderGraph window and clicking Save Asset, and toggling off MSAA in all three RenderPipelineAssets. This breakage with MSAA is case 1184810 which is not introduced nor fixed by this PR, and is still an open issue per Fogbugz.
> 
> In MultiPass stereo mode the right eye is entirely black. This is a separate known issue not introduced or addressed by this PR.
> 
> I found no problems caused by this PR and it fixes some bugs so I am approving.

Will there be a fix for the  MSAA breaking Shader Graph and Worldspace UI rendering?

**Comment by thomas-zeng** [comment]
@ROBYER1 Hi Rob :) This is an Oculus gles driver issue. We started the conversation with Oculus to get this issue fixed.

**Comment by ROBYER1** [comment]
@thomas-zeng Thankyou for the update :) will this be bypassed by Vulkan support then?

**Comment by ROBYER1** [comment]
> @ROBYER1 Hi Rob :) This is an Oculus gles driver issue. We started the conversation with Oculus to get this issue fixed.
> Workaround for the issue is to:
> a) disable MSAA
> b) disable opaqueTexture in URP pipeline setting and make sure there is no render target switch between opaque pass and transparent pass

Hi Thomas,

Is there any update on this? Or if Vulkan for Oculus Android is coming soon, does that circumvent this issue?

**Comment by thomas-zeng** [comment]
Hi @ROBYER1,
This issue is being tracked internally and shared with the oculus team. Oculus is verifying this driver issue.

**Comment by ROBYER1** [comment]
> 1184810

@DennisDeRykeUnity Is there any update on case 1184810? MSAA still causes issues with rendering the UI/Shader Graph and also Fixed-Foveated Rendering on Quest still does not work with UniversalRP at the latest master branch state.

**Comment by DennisDeRykeUnity** [comment]
@ROBYER1 Case 1184810 is currently assigned to one of our developers, but that is all I known about it.

**Comment by lassade** [comment]
> 
> 
> @ROBYER1 Hi Rob :) This is an Oculus gles driver issue. We started the conversation with Oculus to get this issue fixed.
> Workaround for the issue is to:
> a) disable MSAA
> b) disable opaqueTexture in URP pipeline setting and make sure there is no render target switch between opaque pass and transparent pass

By disabling opaqueTexture I was able to keep both transparency and MSAA working with both URP 7.2 and 7.3.

**Pull request merged**
