### PR TITLE
shader graph decal fixups

### PR DESCRIPTION
**Pull request by Paulm-Unity**
### Purpose of this PR
only display allow transparency checkbox for HDRP/decal shaders
add affects albedo and normal checkboxes to decal shader graph
log warning if trying to draw shader graph decals in 3RT mode
fix decal mesh depth bias

---
### Release Notes

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?

**Automated Tests**: What did you setup?

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?

**Halo Effect**: None, Low, Medium, High?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by Paulm-Unity** [comment]
I will the transparency, but for the RT we also specify a colormask, so I am not sure what would happen if there is a mask for an RT that doesn't exist. Perhaps we will get some validation errors in the driver? So I think if we want to support 3RT a solution for that would be to have a 3RT and a 4RT pass. This is what we do for non shader graph decals.

**Comment by sebastienlagarde** [comment]
Yes. Indeed. Let's do that :)

**Comment by Paulm-Unity** [comment]
I pushed the changes, but there seems to be a build error on Mac Intel

https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=hdrp-decal-shader-graph-4&unity_branch=trunk&automation-tools_branch=master

Also for the graphics test, a QA engineer from Spotlight @robertor is interested in getting to know how to work with the HDRP graphics tests, so he would like to work on the test if it is not something that needs to be done right away.

**Comment by sebastienlagarde** [comment]
Hmm... intel test seems to have been triggered on katana for HDRP, which is not expected, but this is unrelated to your PR, change are fine. Merging.

@RobertoR you can contact @RemyUnity for info, but threre is nothing special: 
- open HDRP_Test
- create a scene with a Test camera (you can look at any test to see what component to add).
Doc: https://docs.google.com/document/d/1n4d0BI_8BdLwnH-OMUAAAS8z2RAwJ32i-6MgPwFJDgs/edit?usp=sharing (a bit outdated but still relevant)

**Pull request merged**
