### PR TITLE
Added Test for sampling OpaqueTexture in XR through ShaderGraph

### PR DESCRIPTION
**Pull request by soraryu**
### Purpose of this PR
Opaque Texture sampling in ShaderGraph currently breaks in XR. It's used for a wide variety of effects, e.g. water, blurry refractions, translucency...
This PR adds a test for that.

### Testing status

**Manual Tests**: What did you do?
- [X] Opened test project + Run graphic tests locally
- [X] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [X] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)
New test scene in ShaderGraphUniversalStereo, 003_xr_OpaqueTexture (numbering makes sense with my previous PR which has 002).

_Reference Image_
003_xr_OpaqueTexture

_Multi Pass_
191009-111316-Unity

_Single Pass_

_Single Pass Instanced_

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

---
### Overall Product Risks
**Technical Risk**: None

**Halo Effect**: Low (bugs need to be fixed to make these tests pass)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by soraryu** [comment]
@sophiaaar would be great to get your feedback as well! (I don't have permissions to add reviewers)

**Comment by phi-lira** [comment]
@thomas-zeng @fabien-unity fyi about the opaque texture. We should fix those and look at adding tests for those.

**Comment by phi-lira** [comment]
@soraryu I'm making a compilation of these PRs and will have a sync with XR team next week to figure out the roadmap for both features and fixes. Can you make sure all these issues are also reported on fogbugz? 

Some of the post-processing issues were already fixed and are in PR state.

**Comment by ROBYER1** [comment]
> @soraryu I'm making a compilation of these PRs and will have a sync with XR team next week to figure out the roadmap for both features and fixes. Can you make sure all these issues are also reported on fogbugz?
> 
> Meanwhile hang on with the PR creation as I need to align with them first on what do they expect in terms of taking these external PRs.
> Some of the post-processing issues were already fixed and are in PR state.

I have a series of related issues related to both PRs from Soraryu related to Grabpass, Opaque Texture and 'Unity_StereoEyeIndex' in both URP and Built-In renderer here at the following cases. I ended up making a repro project to directly identify the causes of unwanted water shader behaviour.

1183721, 1183768, 1184447, 1188122, 1188487

Hopefully they are of some use

**Comment by soraryu** [comment]
@phi-lira all my tests are for specific issues also reported in fogbugz. Unfortunately most of my fogbugz issues get either closed as "by design as the team didn't get to this functionality yet" or "internal duplicate" so the case numbers itself are not very helpful.

1185839, 1185837, 1185836, 1185834, 1185832, 1183936, 1193371

About the PR state of the postprocessing issues: I talked a bit with Fabien and I think he took a look at these tests with his branch already. I told him that it fixes some but definitely not all of those issues, tests still fail on specific rendering modes, and when using GPU instancing with ShaderGraph.

**Comment by DennisDeRykeUnity** [comment]
I made dev branch xr_sg_urp_dennisd from SRP master then merged in three dev branches from prefrontalcortex remote per three PRs to be reviewed:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4803
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5022
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4802

On Yamato I have launched "_ABV for SRP repository - fast-trunk" against branch xr_sg_urp_dennisd per link below.  Tomorrow I will compare these test results against SRP master. Also tomorrow in the Editor I plan to examine the new tests introduced by these PRs, and tinker with the screen capture workaround.  
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/xr_sg_urp_dennisd/.yamato%252Fupm-ci-abv.yml%2523all_project_ci_fast-trunk/754717/job

@soraryu Thank you for your contributions.  Sorry that it has taken me a while to start reviewing these.

**Comment by ROBYER1** [comment]
@DennisDeRykeUnity is there any update on this? I would like to see the improvements to testing from those PRs improve the stability of future commits

**Comment by DennisDeRykeUnity** [comment]
@ROBYER1 I had to test upcoming SRP code changes, so I was unable to work on soraryu's trio of PRs for the past few days.  I am revisiting this now, and hoping to bring it to closure this week.

**Comment by DennisDeRykeUnity** [comment]
@soraryu I am closing three of your PRs (#4803, #5022, and#4802) because I merged them into PR #5215 which has been merged into master.  See discussion above.  Thanks again for your contributions!

**Pull request closed without merging**
