### PR TITLE
Vfx graph/mesh volume pcache

### PR DESCRIPTION
**Pull request by RemyUnity**
### Purpose of this PR
Add a mesh volume to pCache bake tool.

---
### Release Notes
See above.

---
### Testing status
Editor only tool tested locally.

---
### Overall Product Risks
**Technical Risk**: Low: Worst case is that the tool fails baking.

**Halo Effect**: Low: Renamed some classes from the other mesh bake tool ('Mesh' -> 'Mesh Surface')

### CODE REVIEW

**Comment by RemyUnity** [comment]
@julienf-unity Yes, true, should be fixed now.

**Comment by VladNeykov** [comment]
Voxel size should be clamped down; negative values throw an exception

**Comment by sebastienlagarde** [comment]
Is this PR still active ?

**Comment by RemyUnity** [comment]
I successfully merged master in this branch locally. Should be safe to marge to master.

**Comment by RemyUnity** [comment]
New PR made : https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/2935

**Pull request closed without merging**
