### PR TITLE
SH sampling as a shader feature

### PR DESCRIPTION
**Pull request by aleks01010101**

### CODE REVIEW

**Comment by pbbastian** [comment]
@aleks01010101 @phi-lira Is this PR still relevant?

**Comment by phi-lira** [comment]
We need the option to avoid sampling SH I'm just not sure about if this is the right way to do it. Aleksandr let's talk about this next week along with shader tiers?

For now let's not remove this PR.

**Comment by aleks01010101** [comment]
Sure, let's do it

**Comment by pbbastian** [comment]
I'm closing the PR meanwhile to keep the list of open PRs somewhat tidy. The PR can still be found under closed PRs, and when all this is ready you can open a new one, or re-open this one.

**Pull request closed without merging**
