### PR TITLE
Fix test framework baking issue [Skip CI]

### PR DESCRIPTION
**Pull request by phi-lira**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Fix baking issue with the graphics test framework. This changes framework to not bake lights additively.

https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/gfxframework%252Ffix-baking-issue

### CODE REVIEW

**Comment by sophiaaar** [comment]
just to confirm, does this fix the issue that VFX was having too? cc @PaulDemeulenaere

**Comment by PaulDemeulenaere** [comment]
> just to confirm, does this fix the issue that VFX was having too? cc @PaulDemeulenaere

To check this, we have to merge `vfx/staging`, I tried to graft this change here : https://github.com/Unity-Technologies/ScriptableRenderPipeline/commit/e4d0b649ac1c4c1e57928d7a8923650c282a3431
But it also fails with the same value, do we have something to do on this scene ?

There is only the label `TestRunnerBake` in meta file for this scene : https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/vfx/test/fix-baking-issue-graft/TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/Shadergraph/SampleScene/101_ShadergraphSampleScene.unity.meta

**Comment by PaulDemeulenaere** [comment]
You can launch VFX_LWRP on this branch, the difference should be only in this red square :
image

**Comment by sophiaaar** [comment]
> You can launch VFX_LWRP on this branch, the difference should be only in this red square

btw the result images will still show up incorrectly until the utr fix is in

**Comment by PaulDemeulenaere** [comment]
PlayMode VFX URP:
image

Standalone VFX URP :
image

I confirm the GI is still missing on this test...

**Comment by sophiaaar** [comment]
should this be closed?

**Comment by phi-lira** [comment]
Closing. Issue was caused by running test in batchmode.

**Pull request closed without merging**
