### PR TITLE
Hdrp decal htile buffer (new)

### PR DESCRIPTION
**Pull request by Paulm-Unity**
### Purpose of this PR
Fixes decal HTile on Metal

---
### Release Notes
Please add any useful notes about the feature/fix that might be helpful for others.

---
### Testing status
**Katana Tests**: First off we need to make sure the Katana SRP tests are green?

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

Launch Katana (Link on master here - update for your branch):
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=master&automation-tools_branch=master&unity_branch=trunk&sort=1-asc

Alternative, launch Yamato (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?

**Halo Effect**: None, Low, Medium, High?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
arf, this PR is cursed: 
Yamato is full of issue... https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/hdrp-decal-htile-buffer-merge-staging/.yamato%252Fupm-ci-hdrp.yml%2523HDRP_Windows64_playmode_DX11_trunk/538701/job/pipeline

**Comment by sebastienlagarde** [comment]
The Pr pass yamato, to be able to make progress on this I will merge it, but we need to validate that all is finr for PS4 and Xbox too

**Comment by TomasKiniulis** [comment]
Adding test page: https://confluence.hq.unity3d.com/pages/viewpage.action?pageId=59078610
The test project linked crashes on Xbox and PS4 with this PR. Unfortunately, I am unable to troubleshoot if it's caused by this PR, because checking on Xbox is also crashing on staging. Will try to continue investigating this on Monday

**Comment by TomasKiniulis** [comment]
We are getting constant crashes on PS4 and Xbox since 2020.1.0a1 which does not reproduce on the legacy pipeline but does on HDRP. It does not seem to be PR dependant. Testing on Xbox it even reproduces on release packages. Until the issue is found, I can't check the PR on consoles 
A ticket is filed here: https://fogbugz.unity3d.com/f/cases/1188480/
Maybe the Xbox or PS4 team can get some more info on the reasoning of the crash. Assigned to them now

**Pull request merged**
