### PR TITLE
[skip CI] Candidate SRP Packages 7.1.7 for smoke testing [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by sebastienlagarde**
This PR contain the local package downloaded from Yamato for the version 7.1.7
and build from latest comit of release/7.1.x

Goal is to have the various stakeholder of the packages to do the smoke testing (big test should have been done before we create those packages) and validate the PR. When everyone have validated we can  try to publish the package via Yamato, or do another round with updated package if fix are required.

### CODE REVIEW

**Comment by DennisDeRykeUnity** [comment]
@sebastienlagarde 
1) What is the target deadline for testers to approve or reject this PR? 
2) Is Unity 2019.3.0f3 (build #9895) the preferred Editor version to test this with?

**Comment by sebastienlagarde** [comment]
> @sebastienlagarde
> 
> 1. What is the target deadline for testers to approve or reject this PR?
> 2. Is Unity 2019.3.0f3 (build #9895) the preferred Editor version to test this with?

We can say Tuesday 17.
Yes Unity 2019.3.0f3 is the preferred binary or latest 2019.3/staging if you have access to it

**Comment by phi-lira** [comment]
for validation I’d like to have template scene test + boat attack.

Additional Things to test:
 Play around with some settings in the pipeline asset and validate they working as expected.
 Build to Android.

**Comment by soraryu** [comment]
Please don't forget these, thanks :)
- Build to Desktop VR
- Use VR in the Editor with Android build target
- Build to Android VR (Quest or Go)

**Comment by sebastienlagarde** [comment]
We have updated the core package with fix for GLES. i.e this issue: https://forum.unity.com/threads/unity-2019-3-0f-error-lodditheringtransition-is-not-supported-on-gles-2-0.792945/

**Comment by VladNeykov** [comment]
VFX is looking good: https://docs.google.com/document/d/1-ybkklf2tR4BAbZ78CiMarWlM6g3Do4fXLRxg4l38cE/edit#
(a few minor fixes making their way in)

**Comment by DennisDeRykeUnity** [comment]
@thomas-zeng As part of your review, could you identify likely pain points for XR, to help me and my peers better focus our testing?  We would like guidance on which XR platforms, graphics features, and stereo modes are most likely to break based on the code changes herein.

**Comment by DennisDeRykeUnity** [comment]
Thomas is on vacation this week and next week, but I got this XR testing guidance from Fabien: 
- Multi Pass stereo mode with Universal RP is the new XR feature being introduced
- For XR the rest should be considered as regression tests
- He suggests using the template scenes on: Quest for Universal RP; DX11 and PSVR for HDRP

I'll get started now with testing the HDRP Template scene on Oculus Rift.

**Comment by sebastienlagarde** [comment]
Note: Updated HDRP/Core/VFX with doc and 2 fix for 2 issues found by testing VFX and HDRP by the QA (Sky and subgraph)

**Comment by sebastienlagarde** [comment]
And a fix for DXR denoiser

**Comment by soraryu** [comment]
@GrantLamb-Unity both current master and this package still break some parts of ShaderGraph for Quest (e.g. case 1201706). Have you tested this? It's a regression to 7.1.1.

**Comment by DennisDeRykeUnity** [comment]
I saw no new bugs while testing this configuration: 
- branch srp/packages-candidates commit 9ae8a17
- Unity 2019.2.0f3 (branch 2019.3/staging changeset 6c9e2bfd6f81) 
- Oculus Rift 
- XR SDK
- Standalone players built from HDRP Template scene
- Multi Pass and Single Pass Instancing stereo modes 

Other configurations are being tested by my XR QA peers.  

@soraryu I regret to inform you that case 1201706 has not yet been resolved.  Also, while I am hopeful that three of your recent PRs can be merged, this has not yet been brought to closure.  Thanks again for submitting those test cases and a workaround for Stereo Instancing screen capture problem.

**Comment by soraryu** [comment]
@DennisDeRykeUnity thanks for confirming. I just wanted to bring this up as this is definitely a new bug / regression to 7.1.1. Texture Arrays in ShaderGraph work fine back there.
It is a "new & blocking issue" as it breaks our project when going from 7.1.1 to current master.

**Comment by sebastienlagarde** [comment]
package 7.1.7 are publised on staging

**Pull request closed without merging**
