### PR TITLE
Do not process lights beyond the specified limit

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Fix https://fogbugz.unity3d.com/f/cases/1189615/ and https://fogbugz.unity3d.com/f/cases/1189622/

---
### Testing status

**Manual Tests**: Yes
**Yamato**: https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline/tree/HDRP%252Ffix-light-limits/.yamato%252Fupm-ci-hdrp.yml%2523All_HDRP/554269/job

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Hey, I need to check the code, it was suppose to be done. Just a note: don't forget changelog :)

**Comment by EvgeniiG** [comment]
Done.

**Comment by EvgeniiG** [comment]
Note that if you don't merge this immediately, you will have conflicts in the changelog file again. It's probably best to edit it right before merging the PR.

**Comment by EvgeniiG** [comment]
Needs testing btw.

**Comment by EvgeniiG** [comment]
I also fixed a related shadow issue.

**Pull request merged**
