### PR TITLE
 Hotfix for Hololens Remote Rendering

### PR DESCRIPTION
**Pull request by phi-lira**
### Purpose of this PR
 Hotfix to improve performance when running Hololens Remote Rendering

---
### Comments to reviewers
 This is a very blind fix as I don't have much experience in XR and I don't have a Hololens device to test the fix.

### CODE REVIEW

**Comment by joejo-unity** [comment]
You should probably loop in our QA as well. Talk to @mario or @JasonCostanza .

**Comment by mario** [comment]
What did I do wrong this time? :D

**Comment by joejo-unity** [comment]
@mario Sorry, wrong Mario! ;-)
 Ignore that.

@phi-lira I meant Mario Baumann.

**Comment by JasonCostanza** [comment]
Is this for Legacy VR or XR SDK?

**Comment by thomas-zeng** [comment]
I know this fix is to work around a driver bug for hololens. Could you provide more info on what driver bug we are trying to workaround? From looking at the code, seems like driver bug is related to intermediate color buffer?

**Comment by phi-lira** [comment]
I'm not sure about current driver bug. To be honest this is a workaround for a HUP issue that degradates performance when taking the intermediate render texture path. 

We need to have a follow up meeting after package is released to track real root cause of issue.

**Comment by thomas-zeng** [comment]
If this is not to work around a driver bug, then I think the issue we are fixing here is more generic. Intermediate render texture path is costly on mobile platforms so in XR that has an impact on oculus quest/go and wmr hololens.

I recall @grayson-unity  is working on fixing oculus extra blit which is also related to this intermediate texture.
Adding grayson to reviewer list.

**Pull request merged**
