### PR TITLE
Don't apply coat mask if slot not connected and value is 0.

### PR DESCRIPTION
**Pull request by russoh**
### Purpose of this PR
Don't use clear coat if value is 0 and slot is disconnected (optimization).

---
### Release Notes
Please add any useful notes about the feature/fix that might be helpful for others.

---
### Testing status
**Katana Tests**: 
https://katana.bf.unity3d.com/projects/com.unity.render-pipelines/builders?ScriptableRenderLoop_branch=sg%2Fcheck-clear-coat&automation-tools_branch=add-platform-filter&unity_branch=2018.3%2Fstaging#

**Manual Tests**: What did you do?
Checked that clear coat is only turned on when value is >0 or slot is connected.

**Automated Tests**: What did you setup?

Any test projects to go with this to help reviewers?

---
### Overall Product Risks
**Technical Risk**: None, Low, Medium, High?
Low
**Halo Effect**: None, Low, Medium, High?
Low
---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
@russoh Mac is failing on timeout. Not sure if this is due to your PR or not, can you check on a mac what is happening?

**Comment by russoh** [comment]
> @russoh Mac is failing on timeout. Not sure if this is due to your PR or not, can you check on a mac what is happening?

Yes, I'll have a look.

**Comment by sebastienlagarde** [comment]
is mac build ok?

**Comment by sebastienlagarde** [comment]
Ah ok, for mac problem is on master already. I will merge and do the backport for 2108.3

**Comment by russoh** [comment]
> Ah ok, for mac problem is on master already. I will merge and do the backport for 2108.3

Great, sounds good. Thank you.

**Pull request merged**
