### PR TITLE
Set the now exposed cascade blend factor to the previous hard-coded v…

### PR DESCRIPTION
**Pull request by egomeh**
### Purpose of this PR

Set the cascade cull blend modifier back to the value it was fixed at in engine.

---
### Release Notes
This should sync with the Unity engine PR that expose this modified value.

---
### Testing status

Manual testing in test project.

---
### Overall Product Risks
**Technical Risk**: Low

**Halo Effect**: Low

---
### Comments to reviewers
As this needs to sync with the engine PR, there might be more iterations on this PR.

The PR for the engine change is: https://ono.unity3d.com/unity/unity/pull-request/85221/_/graphics/shadows/expose-cascade-multiplier

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Hey, can you add a link to the PR where this is happening. thanks

**Comment by egomeh** [comment]
The link is now in the description

**Comment by sebastienlagarde** [comment]
It miss a changelog

**Comment by egomeh** [comment]
I have now changed the changelog. Will add tech-writer for review as well then.

**Pull request merged**
