### PR TITLE
[8.x.x] XR/Fix for case 1218714

### PR DESCRIPTION
**Pull request by thomas-zeng**
### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-2019.3` label. After you backport the PR, the label changes to `backported-2019.3`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR.
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR

Previous Master PR: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5992
As discussed with SG team, this PR should target 8.x.x and 7.x.x. In master branch, the issue should be fixed by https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/4940

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in devloper mode, you have a button at end of resources that check the pathes)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by LandonTownsendUnity** [comment]
Any notes for shadergraph QA besides verifying the bug has been fixed?

**Comment by alindmanUnity** [comment]
> Any notes for shadergraph QA besides verifying the bug has been fixed?

@LandonTownsendUnity Please verify that in Universal, shaders needing to access the IsFrontFace semantic don't have any regressions. Should be good after that.

**Comment by CrazyOldMaurice** [comment]
Tested Version: 2020.1.0a24.3156
Revision: trunk 1f86fad89a55
Built: Tue, 18 Feb 2020 08:31:41 GMT
with Lumin and Oculus Quest.
Was blocked testing Lumin ZI support on desktop due to https://fogbugz.unity3d.com/f/cases/1224527/
but no issues noted on Lumin device or Quest
Approved.

**Comment by thomas-zeng** [comment]
@phi-lira 
Hey Felipe, both XR QA and SG QA verified this fix. Could you review this when you have time this week? Would be nice to land this for 7.3.0

**Comment by phi-lira** [comment]
@thomas-zeng This PR is targeting 8.x.x, where is the PR to fix master?

**Comment by alindmanUnity** [comment]
@phi-lira it was rolled into targets for master

**Pull request merged**
