### PR TITLE
Generate correct depth and shadow passes for LW with alpha clip

### PR DESCRIPTION
**Pull request by Kink3d**
Previously the alpha and clip theshold port contents were not evaluated when creating these passes. Now there is a minimal pass definition for these in C# including only these pixel slots. This means we now only need one C# method to generate a pass in LWRP.

Fixes fogbugz cases 1051822 and 1051834

### CODE REVIEW

**Comment by zadi0648** [comment]
This is going to take a while to test thoroughly :/

**Comment by zadi0648** [comment]
Removing myself; Wyatt reviewed it instead.

**Comment by pbbastian** [comment]
@Kink3d Are Katana tests green for this PR?

**Comment by Kink3d** [comment]
All tests green

**Pull request merged**
